import {Mesh,MeshBasicMaterial,PerspectiveCamera,Raycaster,Vector2,Group,Vector3} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {createHardwareGeometry} from '/Users/vinicius/code/webPod/packages/device/src/hardware-geometry.ts';
import {createRearShellGeometry} from '/Users/vinicius/code/webPod/packages/device/src/product-shell.ts';
import {cutHardwareApertures} from '/Users/vinicius/code/webPod/packages/device/src/hardware-apertures.ts';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form.ts';
import {DEVICE_LAYOUT} from '/Users/vinicius/code/webPod/packages/device/src/layout.ts';
import {completeDeviceEnvelope,deviceEnvelopeBounds} from '/Users/vinicius/code/webPod/packages/device/src/device-envelope.ts';
import {fitPerspectiveCameraToRotationalEnvelope} from '/Users/vinicius/code/webPod/packages/device/src/camera-fit.ts';
const envelope=completeDeviceEnvelope();const fit=fitPerspectiveCameraToRotationalEnvelope(deviceEnvelopeBounds(envelope),{width:1200,height:800,safePadding:34},30);const camera=new PerspectiveCamera(30,1.5,.1,10000);camera.position.set(0,0,fit.distance);camera.lookAt(0,0,0);camera.updateMatrixWorld();const outer=new Group();outer.rotation.set(-Math.PI/4,-12*Math.PI/180,0);const inner=new Group();inner.position.set(...envelope.center.map(n=>-n) as [number,number,number]);outer.add(inner);const mat=new MeshBasicMaterial();const shell=new Mesh(cutHardwareApertures(createRearShellGeometry({...DEVICE_LAYOUT.body,frontThickness:DEFAULT_DEVICE_FORM.frontThickness,rearCrownInset:DEFAULT_DEVICE_FORM.rearCrownInset})),mat);shell.name='steel-shell';inner.add(shell);for(const part of createHardwareGeometry(DEFAULT_DEVICE_FORM)){const mesh=new Mesh(part.geometry,mat);mesh.name=part.name;inner.add(mesh);}outer.updateMatrixWorld(true);for(const y of [75,85,95,105,115,125]){const ray=new Raycaster();ray.setFromCamera(new Vector2(((367.8604+460/2)/1200)*2-1,1-((572.478+y/2)/800)*2),camera);console.log({pixel:[460,y],hits:ray.intersectObject(outer,true).slice(0,2).map(h=>({name:h.object.name,local:inner.worldToLocal(h.point.clone()).toArray()}))});}
