import {pngAlpha} from '../wrapped-witness-4/png-alpha';
import {createStickerCollision} from '/Users/vinicius/code/webPod/packages/device/src/sticker-collision';
import {Group,Mesh,MeshBasicMaterial,PerspectiveCamera,Vector3,Vector2,Raycaster} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry,createRearStickerPeelGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {createStickerGrabPeelGeometry,stickerGrabPeelRegion,stickerCarryPointerOffset,createStickerFreeCarryGeometry,stickerGeometryUvPoint,interpolateStickerCarryGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-free-carry';
import {captureStickerSurfaceGrab} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface-grab';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},source=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),mesh=new Mesh(source,new MeshBasicMaterial()),data=await Bun.file(import.meta.dir+'/../wrapped-witness-7/candidates.json').json(),output=[];
const collider=createStickerCollision(shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'));
for(const r of data.results.filter(r=>r.viewport.width===1280&&r.face==='side')){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.add(mesh);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const ray=new Raycaster();ray.setFromCamera(new Vector2((r.chosen.pickup.point.x/r.rect.width)*2-1,1-r.chosen.pickup.point.y/r.rect.height*2),camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit)throw Error('No hit');const grab=captureStickerSurfaceGrab(placement,art,hit,r.chosen.pickup.point,content,camera,{getBoundingClientRect:()=>r.rect},()=>true);if(!grab?.anchor)throw Error('No anchor');const stages=[];
const region=stickerGrabPeelRegion(art,placement,grab.anchor),dx=r.chosen.release.x-r.chosen.pickup.point.x,dy=r.chosen.release.y-r.chosen.pickup.point.y,length=Math.hypot(dx,dy),baseline=source.clone();baseline.applyMatrix4(content.matrixWorld);const bp=baseline.getAttribute('position'),uvs=source.getAttribute('uv');

const preflight=await Bun.file(import.meta.dir+'/crease-local-ray-feasibility.json').json(),candidate=preflight.find(r=>r.name==='1280-side').stages.find(s=>s.distance===32).intervals.find(s=>s.feasible),f=candidate.f,N=new Vector3(...candidate.N),cameraOrigin=camera.getWorldPosition(new Vector3()),rayDirection=new Vector3(...candidate.G).sub(cameraOrigin).normalize(),sg=candidate.sg,tg=region.edge%2===1?( (1-grab.anchor.uv[1])*art.height-art.visibleBounds[1])/(art.visibleBounds[3]-art.visibleBounds[1]):(grab.anchor.uv[0]*art.width-art.visibleBounds[0])/(art.visibleBounds[2]-art.visibleBounds[0]),[l,top,right,bottom]=art.visibleBounds,width=placement.width*330,height=width*(bottom-top)/(right-l);
const atCrease=(t)=>stickerGeometryUvPoint(source,(l+(1-f)*(right-l))/art.width,1-(top+t*(bottom-top))/art.height).applyMatrix4(content.matrixWorld),C=atCrease(tg);
const arcAt=(lambda)=>{const G=cameraOrigin.clone().addScaledVector(rayDirection,lambda),D=G.clone().sub(C),h=D.dot(N),A=D.clone().addScaledVector(N,-h).normalize(),b=D.dot(A),theta=2*Math.atan2(h,b),R=theta<1e-10?1e20:D.length()/(2*Math.sin(theta/2));return{G,D,A,theta,R,length:theta<1e-10?D.length():R*theta};};
let lo=candidate.low,hi=candidate.high;const leftSign=arcAt(lo).length-sg;for(let k=0;k<40;k++){const mid=(lo+hi)/2,sign=arcAt(mid).length-sg;if(sign*leftSign>=0)lo=mid;else hi=mid;}const lambda=(lo+hi)/2,arc=arcAt(lambda),geometry=source.clone();geometry.applyMatrix4(content.matrixWorld);const p=geometry.getAttribute('position'),uv=geometry.getAttribute('uv'),startTime=performance.now(),collarWidth=6,coreHalf=.125,outerHalf=.1875;
const smooth=(x)=>{const t=Math.max(0,Math.min(1,x));return t*t*(3-2*t);};let modified=0,collarMaxDisplacement=0;for(let i=0;i<p.count;i++){const u=(uv.getX(i)*art.width-l)/(right-l),t=((1-uv.getY(i))*art.height-top)/(bottom-top),s=(f-(1-u))*width;if(s<=0||Math.abs(t-tg)>=outerHalf)continue;const weight=smooth(s/collarWidth)*(1-smooth((Math.abs(t-tg)-coreHalf)/(outerHalf-coreHalf))),desired=atCrease(t).addScaledVector(arc.A,arc.R*Math.sin(s/arc.R)).addScaledVector(N,arc.R*(1-Math.cos(s/arc.R))),old=new Vector3().fromBufferAttribute(p,i);if(weight<1)collarMaxDisplacement=Math.max(collarMaxDisplacement,desired.distanceTo(old));old.lerp(desired,weight);p.setXYZ(i,old.x,old.y,old.z);modified++;}geometry.computeVertexNormals();const constructionMs=performance.now()-startTime,inverse=content.matrixWorld.clone().invert(),mask=await pngAlpha('/Users/vinicius/code/webPod/assets/stickers/playworn/rock/pw-c03-last-encore.png');let minArea=Infinity,minOpaqueArea=Infinity,contacts=0,opaqueContacts=0,unchangedError=0;const witnesses=[];const auditStart=performance.now();for(let i=0;i<geometry.index.count;i+=3){const ids=[0,1,2].map(k=>geometry.index.getX(i+k)),vs=ids.map(id=>new Vector3().fromBufferAttribute(p,id)),area=vs[1].clone().sub(vs[0]).cross(vs[2].clone().sub(vs[0])).length()/2,u=ids.reduce((sum,id)=>sum+uv.getX(id),0)/3,v=ids.reduce((sum,id)=>sum+uv.getY(id),0)/3,alpha=(mask.pixels[Math.min(mask.height-1,Math.max(0,Math.floor((1-v)*mask.height)))*mask.width+Math.min(mask.width-1,Math.max(0,Math.floor(u*mask.width)))]??0)/255;minArea=Math.min(minArea,area);if(alpha>.99)minOpaqueArea=Math.min(minOpaqueArea,area);const hit=collider.intersectsTriangle(...vs.map(v=>v.applyMatrix4(inverse)));if(hit){contacts++;if(alpha>.99)opaqueContacts++;if(witnesses.length<30)witnesses.push({triangle:i/3,ids,area,alpha});}}
for(let i=0;i<p.count;i++){const u=(uv.getX(i)*art.width-l)/(right-l),t=((1-uv.getY(i))*art.height-top)/(bottom-top),s=(f-(1-u))*width;if(s<=0||Math.abs(t-tg)>=outerHalf)unchangedError=Math.max(unchangedError,new Vector3().fromBufferAttribute(p,i).distanceTo(new Vector3().fromBufferAttribute(bp,i)));}
const picked=stickerGeometryUvPoint(geometry,...grab.anchor.uv).project(camera),screen=[(picked.x+1)*r.rect.width/2,(1-picked.y)*r.rect.height/2],pointer=[r.chosen.pickup.point.x+dx/length*32,r.chosen.pickup.point.y+dy/length*32];
await Bun.write(import.meta.dir+'/crease-strip-side32.json',JSON.stringify({fullCreaseMinimumNormalDot:Math.min(...Array.from({length:97},(_,row)=>new Vector3().fromBufferAttribute(source.getAttribute('normal'),row*97+Math.round((1-f)*96)).transformDirection(content.matrixWorld).dot(N))),candidate,lambda,arc:{theta:arc.theta,radius:arc.R,length:arc.length,A:arc.A.toArray(),N:N.toArray()},collar:{normalWidth:collarWidth,coreHalf,outerHalf,endWidth:(outerHalf-coreHalf)*height,maximumUnblendedDisplacement:collarMaxDisplacement},constructionMs,auditMs:performance.now()-auditStart,modified,unchangedError,minArea,minOpaqueArea,contacts,opaqueContacts,witnesses,screen,pointer,pointerError:Math.hypot(screen[0]-pointer[0],screen[1]-pointer[1]),positions:[...p.array],uv:[...uv.array],index:[...geometry.index.array],matrix:content.matrixWorld.toArray(),camera:r.matrices},null,2));geometry.dispose();baseline.dispose();content.remove(mesh);}
collider.dispose();source.dispose();mesh.material.dispose();shell.dispose();
