import {createStickerCollision} from '/Users/vinicius/code/webPod/packages/device/src/sticker-collision';
import {Group,Mesh,MeshBasicMaterial,PerspectiveCamera,Vector3,Vector2,Raycaster} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry,createRearStickerPeelGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {createStickerGrabPeelGeometry,stickerGrabPeelRegion,stickerCarryPointerOffset,createStickerFreeCarryGeometry,stickerGeometryUvPoint,interpolateStickerCarryGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-free-carry';
import {captureStickerSurfaceGrab} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface-grab';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},source=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),mesh=new Mesh(source,new MeshBasicMaterial()),data=await Bun.file(import.meta.dir+'/../wrapped-witness-7/candidates.json').json(),output=[];
const collider=createStickerCollision(shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'));
for(const r of data.results.filter(r=>r.viewport.width===1280)){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.add(mesh);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const ray=new Raycaster();ray.setFromCamera(new Vector2((r.chosen.pickup.point.x/r.rect.width)*2-1,1-r.chosen.pickup.point.y/r.rect.height*2),camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit)throw Error('No hit');const grab=captureStickerSurfaceGrab(placement,art,hit,r.chosen.pickup.point,content,camera,{getBoundingClientRect:()=>r.rect},()=>true);if(!grab?.anchor)throw Error('No anchor');const stages=[];
const region=stickerGrabPeelRegion(art,placement,grab.anchor),dx=r.chosen.release.x-r.chosen.pickup.point.x,dy=r.chosen.release.y-r.chosen.pickup.point.y,length=Math.hypot(dx,dy),baseline=source.clone();baseline.applyMatrix4(content.matrixWorld);const bp=baseline.getAttribute('position'),uvs=source.getAttribute('uv');
for(const distance of [32,57.6]) {
const q=Math.min(1,distance/51.2),crease=region.start+q*(1-region.start),[l,top,right,bottom]=art.visibleBounds,width=placement.width*330,height=width*(bottom-top)/(right-l),materialLength=(crease-region.start)*(region.edge%2===1?width:height),pull={x:dx/length*distance,y:dy/length*distance},anchorWorld=new Vector3(...grab.anchor.point).applyMatrix4(content.matrixWorld),G=anchorWorld.clone().add(stickerCarryPointerOffset(anchorWorld,camera,r.rect.width,r.rect.height,pull.x,pull.y));
const normalizedU=(grab.anchor.uv[0]*art.width-l)/(right-l),normalizedV=((1-grab.anchor.uv[1])*art.height-top)/(bottom-top),tg=region.edge%2===1?normalizedV:normalizedU;
const sample=(t,f=crease)=>{const x=region.edge===1?1-f:region.edge===3?f:t,y=region.edge===0?f:region.edge===2?1-f:t,u=(l+x*(right-l))/art.width,v=1-(top+y*(bottom-top))/art.height;const point=stickerGeometryUvPoint(source,u,v).applyMatrix4(content.matrixWorld);const col=Math.max(0,Math.min(96,Math.round(x*96))),row=Math.max(0,Math.min(96,Math.round(y*96))),normal=new Vector3().fromBufferAttribute(source.getAttribute('normal'),row*97+col).transformDirection(content.matrixWorld);return{t,u,v,point,normal};};
const C=sample(tg).point,D=G.clone().sub(C),samples=Array.from({length:97},(_,i)=>sample(i/96)),sum=samples.reduce((a,s)=>a.add(s.normal),new Vector3()).normalize(),minDot=Math.min(...samples.map(s=>s.normal.dot(sum)));let pair={dot:1,a:0,b:0};for(let i=0;i<samples.length;i++)for(let j=i+1;j<samples.length;j++){const dot=samples[i].normal.dot(samples[j].normal);if(dot<pair.dot)pair={dot,a:i,b:j};}
const local=samples.filter(s=>Math.abs(s.t-tg)<=.125),localSum=local.reduce((a,s)=>a.add(s.normal),new Vector3()).normalize();

const cameraOrigin=camera.getWorldPosition(new Vector3()),rayDirection=G.clone().sub(cameraOrigin).normalize(),originalDepth=G.distanceTo(cameraOrigin),inverse=content.matrixWorld.clone().invert(),hit=collider.castSegment(cameraOrigin.clone().applyMatrix4(inverse),cameraOrigin.clone().addScaledVector(rayDirection,4000).applyMatrix4(inverse)),exteriorMax=hit?hit.point.clone().applyMatrix4(content.matrixWorld).distanceTo(cameraOrigin)-.18:4000,intervals=[];
for(let j=1;j<=64;j++) {const f=region.start+(1-region.start)*j/64,sg=(f-region.start)*(region.edge%2===1?width:height),c=sample(tg,f).point,ns=Array.from({length:97},(_,i)=>sample(i/96,f).normal),N=ns.reduce((a,n)=>a.add(n),new Vector3()).normalize(),normalDot=Math.min(...ns.map(n=>n.dot(N))),toC=c.clone().sub(cameraOrigin),tc=toC.dot(rayDirection),disc=sg*sg-(toC.lengthSq()-tc*tc);let low=0,high=exteriorMax,reason='';if(disc<0)reason='chord quadratic empty';else{low=Math.max(low,tc-Math.sqrt(disc));high=Math.min(high,tc+Math.sqrt(disc));const a=N.dot(cameraOrigin.clone().sub(c)),b=N.dot(rayDirection);if(Math.abs(b)<1e-12){if(a<0)reason='chosen cone parallel outside';}else if(b>0)low=Math.max(low,-a/b);else high=Math.min(high,-a/b);if(low>high)reason='chosen cone/chord/exterior intersection empty';if(normalDot<=0)reason='chosen normal not transverse to every sampled facet';}
const feasible=!reason,lambda=feasible?Math.max(low,Math.min(high,originalDepth)):null,g=lambda===null?null:cameraOrigin.clone().addScaledVector(rayDirection,lambda),d=g?.clone().sub(c),ratio=d?Math.max(0,Math.min(1,d.dot(N)/d.length())):null,arcLength=d&&ratio!==null?ratio<1e-9?d.length():d.length()*Math.asin(ratio)/ratio:null;
intervals.push({f,sg,normalDot,N:N.toArray(),low,high,feasible,reason,lambda,depthDelta:lambda===null?null:lambda-originalDepth,C:c.toArray(),G:g?.toArray(),arcLength,arcMinusMaterial:arcLength===null?null:arcLength-sg});}
stages.push({exteriorMax,originalDepth,intervals,distance,q,crease,edge:region.edge,tg,materialLength,chord:D.length(),feasibleChord:D.length()<=materialLength,D:D.toArray(),C:C.toArray(),G:G.toArray(),normalSum:sum.toArray(),minimumNormalDot:minDot,mostOpposed:pair,localQuarterBand:{minimumNormalDot:Math.min(...local.map(s=>s.normal.dot(localSum))),direction:localSum.toArray(),DdotNormal:D.dot(localSum)},samples:samples.map(s=>({...s,point:s.point.toArray(),normal:s.normal.toArray()}))});
}baseline.dispose();output.push({name:r.viewport.width+'-'+r.face,edge:region.edge,start:region.start,stages});content.remove(mesh);}
await Bun.write(import.meta.dir+'/crease-ray-feasibility.json',JSON.stringify(output,null,2));collider.dispose();console.log(output.map(r=>({name:r.name,stages:r.stages.map(s=>({...s,samples:undefined}))})));source.dispose();mesh.material.dispose();shell.dispose();
