import {pngAlpha} from '../wrapped-witness-4/png-alpha';
import {createStickerDamageField,stickerPixelSurvives} from '/Users/vinicius/code/webPod/packages/device/src/sticker-alpha';
import {Vector3,Matrix4} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerCollision} from '/Users/vinicius/code/webPod/packages/device/src/sticker-collision';
import {stickerSheetTriangleMetric} from '/Users/vinicius/code/webPod/packages/device/src/sticker-sheet-metric';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const smooth=x=>{const t=Math.max(0,Math.min(1,x));return t*t*(3-2*t);};
const mesh=await Bun.file(import.meta.dir+'/curved-crease-side32.json').json(),shell=actualShell(),collider=createStickerCollision(shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support')),inverse=new Matrix4().fromArray(mesh.matrix).invert(),art=getSticker('PW-C03'),[l,top,r,b]=art.visibleBounds,width=115.5,height=width*(b-top)/(r-l),tg=.6980238473730406,f=mesh.candidate.f,stats={};
const mask=await pngAlpha('/Users/vinicius/code/webPod/assets/stickers/playworn/rock/pw-c03-last-encore.png'),field=createStickerDamageField(mask,'PW-C03');
for(let i=0;i<mesh.index.length;i+=3){const ids=mesh.index.slice(i,i+3),rest=ids.map(id=>({x:(mesh.uv[id*2]*art.width-l)/(r-l)*width,y:((1-mesh.uv[id*2+1])*art.height-top)/(b-top)*height})),vertices=ids.map(id=>new Vector3(...mesh.positions.slice(id*3,id*3+3))),u=rest.reduce((s,p)=>s+p.x/width,0)/3,t=rest.reduce((s,p)=>s+p.y/height,0)/3,s=(f*(1-smooth((Math.abs(t-tg)-.125)/.0625))-(1-u))*width,kind=rest.every(p=>{const t=p.y/height,s=(f*(1-smooth((Math.abs(t-tg)-.125)/.0625))-(1-p.x/width))*width;return s<=0||Math.abs(t-tg)>=.1875;})?'untouched':s<=0||Math.abs(t-tg)>=.1875?'crease-boundary-crossing':s<6?'crease-collar':Math.abs(t-tg)>.125?'curved-outlet':'core',metric=stickerSheetTriangleMetric(rest,vertices),hit=collider.intersectsTriangle(...vertices.map(v=>v.clone().applyMatrix4(inverse)));const slot=stats[kind]??={triangles:0,contacts:0,occupiedContacts:0,occupiedMaximumStretch:0,occupiedMinimumStretch:Infinity,occupiedWitnesses:[],minimumStretch:Infinity,maximumStretch:0,minimumAreaRatio:Infinity,worst:null};const pu=ids.reduce((s,id)=>s+mesh.uv[id*2],0)/3,pv=ids.reduce((s,id)=>s+mesh.uv[id*2+1],0)/3,px=Math.min(mask.width-1,Math.max(0,Math.floor(pu*mask.width))),py=Math.min(mask.height-1,Math.max(0,Math.floor((1-pv)*mask.height))),occupied=(mask.pixels[py*mask.width+px]??0)>250&&stickerPixelSurvives(field,px,py,1);slot.triangles++;if(hit)slot.contacts++;if(occupied&&metric){slot.occupiedMaximumStretch=Math.max(slot.occupiedMaximumStretch,metric.maximumStretch);slot.occupiedMinimumStretch=Math.min(slot.occupiedMinimumStretch,metric.minimumStretch);if(hit){slot.occupiedContacts++;slot.occupiedWitnesses.push({triangle:i/3,ids,uv:[pu,pv],minimumStretch:metric.minimumStretch,maximumStretch:metric.maximumStretch,world:vertices.map(v=>v.toArray())});}}if(metric){slot.minimumStretch=Math.min(slot.minimumStretch,metric.minimumStretch);slot.maximumStretch=Math.max(slot.maximumStretch,metric.maximumStretch);if(metric.areaRatio<slot.minimumAreaRatio){slot.minimumAreaRatio=metric.areaRatio;slot.worst={triangle:i/3,ids,minimumStretch:metric.minimumStretch,maximumStretch:metric.maximumStretch,areaRatio:metric.areaRatio};}}}
await Bun.write(import.meta.dir+'/curved-crease-audit.json',JSON.stringify(stats,null,2));console.log(stats);collider.dispose();shell.dispose();
