import {Group,Mesh,MeshBasicMaterial,PerspectiveCamera,Vector3,Vector2,Raycaster} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry,createRearStickerPeelGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {createStickerGrabPeelGeometry,stickerGrabPeelRegion,stickerCarryPointerOffset,createStickerFreeCarryGeometry,stickerGeometryUvPoint,interpolateStickerCarryGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-free-carry';
import {captureStickerSurfaceGrab} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface-grab';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},source=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),mesh=new Mesh(source,new MeshBasicMaterial()),data=await Bun.file(import.meta.dir+'/../wrapped-witness-7/candidates.json').json(),output=[];
for(const r of data.results){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.add(mesh);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const ray=new Raycaster();ray.setFromCamera(new Vector2((r.chosen.pickup.point.x/r.rect.width)*2-1,1-r.chosen.pickup.point.y/r.rect.height*2),camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit)throw Error('No hit');const grab=captureStickerSurfaceGrab(placement,art,hit,r.chosen.pickup.point,content,camera,{getBoundingClientRect:()=>r.rect},()=>true);if(!grab?.anchor)throw Error('No anchor');const stages=[];
const region=stickerGrabPeelRegion(art,placement,grab.anchor),dx=r.chosen.release.x-r.chosen.pickup.point.x,dy=r.chosen.release.y-r.chosen.pickup.point.y,length=Math.hypot(dx,dy),baseline=source.clone();baseline.applyMatrix4(content.matrixWorld);const bp=baseline.getAttribute('position'),uvs=source.getAttribute('uv');
for(const distance of[0,.064,.128,1,2,8,16,20,32,48,51.2,54.4,57.6,60.8,64,length]){const q=Math.min(1,distance/64/.8),transport=Math.max(0,Math.min(1,(distance/64-.8)/.2)),curl=distance<=64?distance/64:1-Math.min(1,(distance-64)/100)*.6,pull={x:dx/length*distance,y:dy/length*distance};const peeled=createStickerGrabPeelGeometry(source,art,placement,grab.anchor,content.matrixWorld,camera,q,pull,r.rect.width,r.rect.height),free=createStickerFreeCarryGeometry(art,placement,source,content.matrixWorld,camera,grab.anchor,curl),anchorWorld=new Vector3(...grab.anchor.point).applyMatrix4(content.matrixWorld),delta=stickerCarryPointerOffset(anchorWorld,camera,r.rect.width,r.rect.height,pull.x,pull.y);free.translate(delta.x,delta.y,delta.z);if(transport>0)interpolateStickerCarryGeometry(peeled,free,...grab.anchor.uv,transport);const p=peeled.getAttribute('position');let minimumArea=Infinity,zero=0,minimumNormalDot=1,outsideMaxError=0;const a=new Vector3(),b=new Vector3(),c=new Vector3(),aa=new Vector3(),bb=new Vector3(),cc=new Vector3();for(let i=0;i<peeled.index.count;i+=3){const ia=peeled.index.getX(i),ib=peeled.index.getX(i+1),ic=peeled.index.getX(i+2);a.fromBufferAttribute(p,ia);b.fromBufferAttribute(p,ib);c.fromBufferAttribute(p,ic);const cross=b.sub(a).cross(c.sub(a)),area=cross.length()/2;minimumArea=Math.min(minimumArea,area);if(area<1e-9)zero++;if(transport===0){aa.fromBufferAttribute(bp,ia);bb.fromBufferAttribute(bp,ib);cc.fromBufferAttribute(bp,ic);minimumNormalDot=Math.min(minimumNormalDot,cross.normalize().dot(bb.sub(aa).cross(cc.sub(aa)).normalize()));}}
const[left,top,right,bottom]=art.visibleBounds,crease=region.start+q*(1-region.start);if(transport===0)for(let i=0;i<p.count;i++){const u=(uvs.getX(i)*art.width-left)/(right-left),v=((1-uvs.getY(i))*art.height-top)/(bottom-top);if(region.coordinate(u,v)>=crease)outsideMaxError=Math.max(outsideMaxError,Math.abs(p.getX(i)-bp.getX(i)),Math.abs(p.getY(i)-bp.getY(i)),Math.abs(p.getZ(i)-bp.getZ(i)));}
const picked=stickerGeometryUvPoint(peeled,...grab.anchor.uv).project(camera),screen={x:(picked.x+1)*r.rect.width/2,y:(1-picked.y)*r.rect.height/2},pointer={x:r.chosen.pickup.point.x+pull.x,y:r.chosen.pickup.point.y+pull.y};stages.push({distance,q,transport,curl,finite:[...p.array].every(Number.isFinite),minimumArea,zero,minimumNormalDot:transport===0?minimumNormalDot:null,outsideMaxError,screen,pointer,pointerError:Math.hypot(screen.x-pointer.x,screen.y-pointer.y)});peeled.dispose();free.dispose();}baseline.dispose();output.push({name:r.viewport.width+'-'+r.face,edge:region.edge,start:region.start,stages});content.remove(mesh);}
await Bun.write(import.meta.dir+'/grabbed-kernel-result.json',JSON.stringify(output,null,2));console.log(output);source.dispose();mesh.material.dispose();shell.dispose();
