import {Group,Mesh,MeshBasicMaterial,PerspectiveCamera,Vector3} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry,createRearStickerPeelGeometry,stickerVisibleAspect} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {stickerGeometryUvPoint} from '/Users/vinicius/code/webPod/packages/device/src/sticker-free-carry';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},source=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),data=await Bun.file(import.meta.dir+'/../wrapped-witness-7/candidates.json').json(),output=[];
for(const r of data.results){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const project=(point)=>{const p=point.clone().applyMatrix4(content.matrixWorld).project(camera);return{x:r.rect.left+(p.x+1)*r.rect.width/2,y:r.rect.top+(1-p.y)*r.rect.height/2};};const uv=r.chosen.pickup.uv,sourcePoint=stickerGeometryUvPoint(source,...uv),sourceScreen=project(sourcePoint),height=115.5*stickerVisibleAspect(art),direction={x:r.chosen.release.x-r.chosen.pickup.point.x,y:r.chosen.release.y-r.chosen.pickup.point.y},length=Math.hypot(direction.x,direction.y),stages=[];
for(const distance of[0,16,32,51.2]){const curl=distance/64,frontier=Math.min(1,curl/.8),peeled=createRearStickerPeelGeometry(art,placement,shell.rear,curl,source,frontier),point=stickerGeometryUvPoint(peeled,...uv),screen=project(point),pointer={x:r.chosen.pickup.point.x+direction.x/length*distance,y:r.chosen.pickup.point.y+direction.y/length*distance};stages.push({distance,curl,frontier,detachedMaterialLength:height*frontier,sourceScreen,peeledScreen:screen,pointer,pointDisplacementModel:point.distanceTo(sourcePoint),pointerError:Math.hypot(screen.x-pointer.x,screen.y-pointer.y),offset:null,depthLift:0});peeled.dispose();}output.push({name:r.viewport.width+'-'+r.face,pickedUV:uv,pickedRow:((1-uv[1])*art.height-art.visibleBounds[1])/(art.visibleBounds[3]-art.visibleBounds[1])*96,stages});}
await Bun.write(import.meta.dir+'/partial-trace.json',JSON.stringify(output,null,2));console.log(output);source.dispose();shell.dispose();
