import {createStickerCollision} from '/Users/vinicius/code/webPod/packages/device/src/sticker-collision';
import {pngAlpha} from '../wrapped-witness-4/png-alpha';
import {Group,Mesh,MeshBasicMaterial,PerspectiveCamera,Vector3,Vector2,Raycaster} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry,createRearStickerPeelGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {createStickerGrabPeelGeometry,stickerGrabPeelRegion,stickerCarryPointerOffset,createStickerFreeCarryGeometry,stickerGeometryUvPoint,interpolateStickerCarryGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-free-carry';
import {captureStickerSurfaceGrab} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface-grab';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},source=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),mesh=new Mesh(source,new MeshBasicMaterial()),data=await Bun.file(import.meta.dir+'/../wrapped-witness-7/candidates.json').json(),output=[];
const collider=createStickerCollision(shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support')),mask=await pngAlpha('/Users/vinicius/code/webPod/assets/stickers/playworn/rock/pw-c03-last-encore.png');
for(const r of data.results.filter(r=>r.viewport.width===1280)){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.add(mesh);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const ray=new Raycaster();ray.setFromCamera(new Vector2((r.chosen.pickup.point.x/r.rect.width)*2-1,1-r.chosen.pickup.point.y/r.rect.height*2),camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit)throw Error('No hit');const grab=captureStickerSurfaceGrab(placement,art,hit,r.chosen.pickup.point,content,camera,{getBoundingClientRect:()=>r.rect},()=>true);if(!grab?.anchor)throw Error('No anchor');const stages=[];
const region=stickerGrabPeelRegion(art,placement,grab.anchor),dx=r.chosen.release.x-r.chosen.pickup.point.x,dy=r.chosen.release.y-r.chosen.pickup.point.y,length=Math.hypot(dx,dy),baseline=source.clone();baseline.applyMatrix4(content.matrixWorld);const bp=baseline.getAttribute('position'),uvs=source.getAttribute('uv');
for(const distance of[16,32,51.2,57.6,64]){const q=Math.min(1,distance/64/.8),transport=Math.max(0,Math.min(1,(distance/64-.8)/.2)),curl=distance<=64?distance/64:1-Math.min(1,(distance-64)/100)*.6,pull={x:dx/length*distance,y:dy/length*distance};const peeled=createStickerGrabPeelGeometry(source,art,placement,grab.anchor,content.matrixWorld,camera,q,pull,r.rect.width,r.rect.height),free=createStickerFreeCarryGeometry(art,placement,source,content.matrixWorld,camera,grab.anchor,curl),anchorWorld=new Vector3(...grab.anchor.point).applyMatrix4(content.matrixWorld),delta=stickerCarryPointerOffset(anchorWorld,camera,r.rect.width,r.rect.height,pull.x,pull.y);free.translate(delta.x,delta.y,delta.z);if(transport>0)interpolateStickerCarryGeometry(peeled,free,...grab.anchor.uv,transport);const p=peeled.getAttribute('position');let minimumArea=Infinity,zero=0,minimumNormalDot=1,outsideMaxError=0;const a=new Vector3(),b=new Vector3(),c=new Vector3(),aa=new Vector3(),bb=new Vector3(),cc=new Vector3();for(let i=0;i<peeled.index.count;i+=3){const ia=peeled.index.getX(i),ib=peeled.index.getX(i+1),ic=peeled.index.getX(i+2);a.fromBufferAttribute(p,ia);b.fromBufferAttribute(p,ib);c.fromBufferAttribute(p,ic);const cross=b.sub(a).cross(c.sub(a)),area=cross.length()/2;minimumArea=Math.min(minimumArea,area);if(area<1e-9)zero++;if(transport===0){aa.fromBufferAttribute(bp,ia);bb.fromBufferAttribute(bp,ib);cc.fromBufferAttribute(bp,ic);minimumNormalDot=Math.min(minimumNormalDot,cross.normalize().dot(bb.sub(aa).cross(cc.sub(aa)).normalize()));}}
const[left,top,right,bottom]=art.visibleBounds,crease=region.start+q*(1-region.start);if(transport===0)for(let i=0;i<p.count;i++){const u=(uvs.getX(i)*art.width-left)/(right-left),v=((1-uvs.getY(i))*art.height-top)/(bottom-top);if(region.coordinate(u,v)>=crease)outsideMaxError=Math.max(outsideMaxError,Math.abs(p.getX(i)-bp.getX(i)),Math.abs(p.getY(i)-bp.getY(i)),Math.abs(p.getZ(i)-bp.getZ(i)));}

const inverse=content.matrixWorld.clone().invert(),crossings=[],shellCounts={},triangleWitness=[];let opaqueMoved=0;const pp=new Vector3(),sp=new Vector3();
for(let i=0;i<p.count;i++){const u=uvs.getX(i),v=uvs.getY(i),alpha=(mask.pixels[Math.min(mask.height-1,Math.max(0,Math.floor((1-v)*mask.height)))*mask.width+Math.min(mask.width-1,Math.max(0,Math.floor(u*mask.width)))]??0)/255;if(alpha<.99)continue;pp.fromBufferAttribute(p,i).applyMatrix4(inverse);sp.fromBufferAttribute(bp,i).applyMatrix4(inverse);const travel=pp.distanceTo(sp);if(travel<1e-5)continue;opaqueMoved++;const h=collider.castSegment(sp,pp);if(h&&h.distance<travel-1e-5){shellCounts[h.source]=(shellCounts[h.source]??0)+1;const screenPoint=pp.clone().applyMatrix4(content.matrixWorld).project(camera);crossings.push({index:i,uv:[u,v],alpha,source:h.source,travel,hitDistance:h.distance,remaining:travel-h.distance,from:sp.toArray(),to:pp.toArray(),shellPoint:h.point.toArray(),screen:[(screenPoint.x+1)*r.rect.width/2,(1-screenPoint.y)*r.rect.height/2]});}}
for(let i=0;i<peeled.index.count;i+=3){const ids=[0,1,2].map(k=>peeled.index.getX(i+k)),vertices=ids.map(id=>new Vector3().fromBufferAttribute(p,id)),cross=vertices[1].clone().sub(vertices[0]).cross(vertices[2].clone().sub(vertices[0])),area=cross.length()/2;const u=ids.reduce((a,id)=>a+uvs.getX(id),0)/3,v=ids.reduce((a,id)=>a+uvs.getY(id),0)/3,alpha=(mask.pixels[Math.min(mask.height-1,Math.max(0,Math.floor((1-v)*mask.height)))*mask.width+Math.min(mask.width-1,Math.max(0,Math.floor(u*mask.width)))]??0)/255;if(alpha>.99){const centroid=vertices[0].clone().add(vertices[1]).add(vertices[2]).multiplyScalar(1/3),view=camera.getWorldPosition(new Vector3()).sub(centroid).normalize();triangleWitness.push({triangle:i/3,ids,area,alpha,facing:cross.normalize().dot(view),uv:[u,v]});}}
triangleWitness.sort((a,b)=>a.area-b.area);
const picked=stickerGeometryUvPoint(peeled,...grab.anchor.uv).project(camera),screen={x:(picked.x+1)*r.rect.width/2,y:(1-picked.y)*r.rect.height/2},pointer={x:r.chosen.pickup.point.x+pull.x,y:r.chosen.pickup.point.y+pull.y};stages.push({opaqueMoved,crossingCount:crossings.length,shellCounts,crossings,smallestOpaqueTriangles:triangleWitness.slice(0,12),distance,q,transport,curl,finite:[...p.array].every(Number.isFinite),minimumArea,zero,minimumNormalDot:transport===0?minimumNormalDot:null,outsideMaxError,screen,pointer,pointerError:Math.hypot(screen.x-pointer.x,screen.y-pointer.y)});peeled.dispose();free.dispose();}baseline.dispose();output.push({name:r.viewport.width+'-'+r.face,edge:region.edge,start:region.start,stages});content.remove(mesh);}
await Bun.write(import.meta.dir+'/phase-classification.json',JSON.stringify(output,null,2));console.log(output.map(r=>({name:r.name,stages:r.stages.map(s=>({distance:s.distance,crossings:s.crossingCount,shellCounts:s.shellCounts,minOpaque:s.smallestOpaqueTriangles[0]}))})));collider.dispose();source.dispose();mesh.material.dispose();shell.dispose();
