import {Group,Mesh,MeshBasicMaterial,PerspectiveCamera,Vector3,Vector2,Raycaster} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry,createRearStickerPeelGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {createStickerFreeCarryGeometry,stickerGeometryUvPoint,interpolateStickerCarryGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-free-carry';
import {captureStickerSurfaceGrab} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface-grab';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},source=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),mesh=new Mesh(source,new MeshBasicMaterial()),data=await Bun.file(import.meta.dir+'/../wrapped-witness-7/candidates.json').json(),output=[];
for(const r of data.results){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.add(mesh);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const ray=new Raycaster();ray.setFromCamera(new Vector2((r.chosen.pickup.point.x/r.rect.width)*2-1,1-r.chosen.pickup.point.y/r.rect.height*2),camera);const hit=ray.intersectObject(mesh,false)[0];if(!hit)throw Error('No hit');const grab=captureStickerSurfaceGrab(placement,art,hit,r.chosen.pickup.point,content,camera,{getBoundingClientRect:()=>r.rect},()=>true);if(!grab?.anchor)throw Error('No anchor');const stages=[];
for(const [transport,curl] of[...Array.from({length:21},(_,i)=>[i/20,.8+.2*i/20]),[1e-6,.8000002],[1-1e-6,.9999998],[1,.497049]]){const peeled=createRearStickerPeelGeometry(art,placement,shell.rear,curl,source,1);peeled.applyMatrix4(content.matrixWorld);const free=createStickerFreeCarryGeometry(art,placement,source,content.matrixWorld,camera,grab.anchor,curl),p=peeled.getAttribute('position'),fp=free.getAttribute('position');interpolateStickerCarryGeometry(peeled,free,...grab.anchor.uv,transport);let minimumArea=Infinity,zero=0;const a=new Vector3(),b=new Vector3(),c=new Vector3();for(let i=0;i<peeled.index.count;i+=3){a.fromBufferAttribute(p,peeled.index.getX(i));b.fromBufferAttribute(p,peeled.index.getX(i+1));c.fromBufferAttribute(p,peeled.index.getX(i+2));const area=b.sub(a).cross(c.sub(a)).length()/2;minimumArea=Math.min(minimumArea,area);if(area<1e-9)zero++;}const picked=stickerGeometryUvPoint(peeled,...grab.anchor.uv),expected=new Vector3(...grab.anchor.point).applyMatrix4(content.matrixWorld);stages.push({transport,curl,finite:[...p.array].every(Number.isFinite),minimumArea,zero,pickedAnchorDistance:picked.distanceTo(expected)});if(transport===1&&curl===.497049)await Bun.write(import.meta.dir+'/'+r.viewport.width+'-'+r.face+'-free.json',JSON.stringify({positions:[...p.array],uv:[...peeled.getAttribute('uv').array],indices:[...peeled.index.array],anchor:grab.anchor}));peeled.dispose();free.dispose();}output.push({name:r.viewport.width+'-'+r.face,stages});content.remove(mesh);}
await Bun.write(import.meta.dir+'/result.json',JSON.stringify(output,null,2));console.log(output);source.dispose();mesh.material.dispose();shell.dispose();
