import {Group,PerspectiveCamera,Vector2,Mesh,MeshBasicMaterial,Raycaster} from '/Users/vinicius/code/webPod/packages/device/node_modules/three/build/three.module.js';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {captureStickerSurfaceGrab} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface-grab';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1};

const shown=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),mesh=new Mesh(shown,new MeshBasicMaterial());
const old=await Bun.file(import.meta.dir+'/../wrapped-witness-6/candidates.json').json(),results=[];
for(const r of old.results){const content=new Group();content.matrixAutoUpdate=false;content.matrix.fromArray(r.matrices.contentWorld);content.add(mesh);content.updateMatrixWorld(true);const camera=new PerspectiveCamera();camera.matrixAutoUpdate=false;camera.matrix.fromArray(r.matrices.cameraWorld);camera.updateMatrixWorld(true);camera.projectionMatrix.fromArray(r.matrices.cameraProjection);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();const ray=new Raycaster();ray.setFromCamera(new Vector2(2*(r.chosen.pickup.point.x-r.rect.left)/r.rect.width-1,1-2*(r.chosen.pickup.point.y-r.rect.top)/r.rect.height),camera);const probe=new Mesh(mesh.geometry,mesh.material);probe.matrixWorld.copy(mesh.matrixWorld);const before=probe.matrixWorld.toArray();const hit=ray.intersectObject(probe,false)[0];if(!hit)throw Error('No source hit');const grab=captureStickerSurfaceGrab(placement,art,hit,r.chosen.pickup.point,content,camera,{getBoundingClientRect:()=>r.rect},()=>true);const path=[];for(const t of r.chosen.trajectory){const center=t.admitted?grab?.projectCenter(t.point.x,t.point.y):null;let error=null;if(center){try{const g=createStickerSurfaceGeometry(art,{...placement,...center},shell.rear,wrap);if(![...g.getAttribute('position').array].every(Number.isFinite))error='nonfinite';g.dispose();}catch(e){error=String(e);}}path.push({point:t.point,admitted:t.admitted,center,error});}results.push({name:r.viewport.width+'-'+r.face,before,after:probe.matrixWorld.toArray(),valid:grab?.isValid(),path});content.remove(mesh);}
await Bun.write(import.meta.dir+'/result.json',JSON.stringify(results,null,2));console.log(results.map(r=>({name:r.name,nulls:r.path.filter(t=>t.admitted&&!t.center).length,errors:r.path.filter(t=>t.error).length,last:r.path.at(-1)})));mesh.material.dispose();shown.dispose();shell.dispose();
