import assert from 'node:assert/strict';
import {Mesh} from '../../../../../../packages/device/node_modules/three/build/three.module.js';
import {prepareStickerPackRenderFrame} from '../../../../../../packages/device/src/sticker-pack-render-frame';
import {prepareStickerRenderFrame} from '../../../../../../packages/device/src/sticker-render-frame';
import {prepareStickerPackGeometry} from '../../../../../../packages/device/src/sticker-pack-resource-data';
import {drainSteps} from '../../../../../../packages/device/src/sticker-computation-steps';
import {stickerPackGeometryKey,stickerPackSleeveParts,type StickerPackNode,type StickerPackGeometryInput} from '../../../../../../packages/device/src/sticker-pack-recipe';
import {stickerPackLeafSlots} from '../../../../../../packages/device/src/sticker-pack-graph';
const size={width:100,height:140,pixel:.2};
const recipe:StickerPackNode={kind:'group',id:'root',position:[8,9,130],rotation:[.1,.4,.02],children:[{kind:'paper',id:'paper',size,ink:'#abc',liner:true,curl:.6,epoch:1},{kind:'sleeve',id:'sleeve',size,ink:'#bca',position:[0,0,2]}]};
const inputs:StickerPackGeometryInput[]=[{kind:'gpu-paper',...size,liner:true},...stickerPackSleeveParts(size).map(part=>part.geometry)];
const unique=[...new Map(inputs.map(input=>[stickerPackGeometryKey(input),input])).values()];
const ports=unique.map((input,index)=>{const channel=new MessageChannel();return {input,id:index+1,channel};});
const pending=prepareStickerPackRenderFrame({key:'proof',recipe,geometry:ports.map(({input,id,channel})=>({key:stickerPackGeometryKey(input),id,port:channel.port2})),damage:[],artworks:[],prints:[]},null,new AbortController().signal);
for(const {input,id,channel}of ports)channel.port1.postMessage({version:1,id,value:drainSteps(prepareStickerPackGeometry(input))});
const frame=await pending;frame.root.updateWorldMatrix(true,true);
const slots=stickerPackLeafSlots(recipe);assert.equal(frame.root.children.length,slots.length);
let meshes=0,geometryDisposals=0,materialDisposals=0;const geometries=new Set(),materials=new Set();
frame.root.traverse(object=>{if(!(object instanceof Mesh))return;meshes++;if(!geometries.has(object.geometry)){geometries.add(object.geometry);object.geometry.addEventListener('dispose',()=>geometryDisposals++);}for(const material of Array.isArray(object.material)?object.material:[object.material]){if(materials.has(material))continue;materials.add(material);material.addEventListener('dispose',()=>materialDisposals++);}if(object.parent===frame.root.children[0])assert.equal(object.frustumCulled,false);});
assert.equal(meshes,7);
frame.update({...recipe,position:[1,2,3]});assert.deepEqual(frame.root.position.toArray(),[1,2,3]);
frame.dispose();frame.dispose();assert.equal(geometryDisposals,geometries.size);assert.equal(materialDisposals,materials.size);for(const {channel}of ports)channel.port1.close();
const packChannel=new MessageChannel(),packAbort=new AbortController();
const aborted=prepareStickerPackRenderFrame({key:'abort',recipe,geometry:[{key:'pending',id:9,port:packChannel.port2}],damage:[],artworks:[],prints:[]},null,packAbort.signal);packAbort.abort();await assert.rejects(aborted,{name:'AbortError'});packChannel.port1.close();
const channel=new MessageChannel(),abort=new AbortController();
const equipped=prepareStickerRenderFrame({sequence:1,computationEpoch:1,prints:[],artworks:[],resources:[{id:1,port:channel.port2}]},null,abort.signal);abort.abort();await assert.rejects(equipped,{name:'AbortError'});channel.port1.close();
const bad=new MessageChannel();const mismatch=prepareStickerRenderFrame({sequence:2,computationEpoch:1,prints:[],artworks:[],resources:[{id:1,port:bad.port2}]},null,new AbortController().signal);bad.port1.postMessage({version:1,id:2,result:{}});await assert.rejects(mismatch,/identity mismatch/);bad.port1.close();
await Bun.write(new URL('./reviewer-lifecycle.json',import.meta.url),JSON.stringify({meshes,geometryDisposals,materialDisposals,idempotentDispose:true,packAbort:true,equippedAbort:true,identityMismatch:true},null,2)+'\n');
