import { expect, test } from '../../../packages/panel/node_modules/@playwright/test/index.mjs'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { installDeterministicAppleMusic } from './deterministic-apple-music'
import { assertBrowserSourceIdentity } from './source-identity'

const evidence = resolve(import.meta.dirname, '../../../docs/workstreams/007-device-shell-polish/evidence/settings')
test.use({ launchOptions: { executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--enable-blink-features=CanvasDrawElement'] } })
test.beforeAll(async () => { await mkdir(evidence, { recursive: true }) })
test.beforeEach(async ({ page }) => {
  await installDeterministicAppleMusic(page)
  await page.goto('/')
  await assertBrowserSourceIdentity(page)
  await expect(page.locator('.wp-panel')).toHaveAttribute('data-screen', 'S03')
})

test('settings are hidden until activation and preserve live preferences through dismissal', async ({ page }) => {
  const dialog = page.getByRole('dialog', { name: 'Settings' })
  const trigger = page.getByRole('button', { name: 'Settings', exact: true })
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Silver', exact: true })).not.toBeVisible()
  await expect(page.getByRole('region', { name: 'Apple playback diagnostics' })).not.toBeVisible()
  await page.screenshot({ path: resolve(evidence, 'settings-closed.png') })
  await trigger.click()
  await expect(dialog).toBeVisible()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(dialog.getByRole('button', { name: 'Close', exact: true })).toBeFocused()
  await page.screenshot({ path: resolve(evidence, 'settings-open-dark.png') })
  await dialog.getByRole('button', { name: 'Silver', exact: true }).click()
  await dialog.getByRole('button', { name: 'Light room' }).click()
  const sound = dialog.getByRole('button', { name: 'Click-wheel sound' })
  await expect(sound).toHaveAttribute('aria-pressed', 'true')
  await sound.click()
  await expect(sound).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('main')).toHaveAttribute('data-colourway', 'white')
  await expect(page.locator('main')).toHaveAttribute('data-room', 'light')
  await expect(dialog.getByRole('button', { name: 'Close', exact: true })).toHaveCSS('background-color', 'rgb(34, 43, 56)')
  await page.screenshot({ path: resolve(evidence, 'settings-open.png') })
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.press('Enter')
  await expect(dialog).toBeVisible()
  await expect(sound).toHaveAttribute('aria-pressed', 'false')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})

test('keyboard stays inside settings and playback and rotation resume after closing', async ({ page }) => {
  await page.evaluate(() => {
    const music = Reflect.get(globalThis, 'MusicKit').getInstance()
    music.play = async () => { music.playbackState = 3; music.__emit('playbackStateDidChange') }
    music.pause = async () => { music.playbackState = 2; music.__emit('playbackStateDidChange') }
  })
  const panel = page.locator('.wp-panel')
  await panel.focus()
  await panel.press('Enter')
  await panel.press('Enter')
  await panel.press('Enter')
  await expect(panel).toHaveAttribute('data-screen', 'S13')
  await expect.poll(() => page.evaluate(() => Reflect.get(globalThis, 'MusicKit').getInstance().playbackState)).toBe(3)
  const trigger = page.getByRole('button', { name: 'Settings', exact: true })
  await trigger.focus()
  await trigger.press('Space')
  const dialog = page.getByRole('dialog', { name: 'Settings' })
  await expect(dialog).toBeVisible()
  for (let index = 0; index < 14; index++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate((node) => node.contains(document.activeElement))).toBe(true)
  }
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Home')
  await expect(page.locator('main')).toHaveAttribute('data-pose', 'front')
  await expect(panel).toHaveAttribute('data-screen', 'S13')
  await page.keyboard.press('Escape')
  await expect(dialog).not.toBeVisible()
  const stage = page.getByRole('region', { name: 'Three-dimensional iPod preview', exact: false })
  await stage.focus()
  await stage.press('ArrowRight')
  await expect(page.locator('main')).toHaveAttribute('data-pose', 'custom')
  await page.getByRole('button', { name: 'Reset view' }).click()
  await expect(page.locator('main')).toHaveAttribute('data-pose', 'front')
  await panel.focus()
  await panel.press('Space')
  await expect.poll(() => page.evaluate(() => Reflect.get(globalThis, 'MusicKit').getInstance().playbackState)).toBe(2)
})

test('settings remain usable on a small viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Settings' })
  const box = await dialog.boundingBox()
  expect(box).not.toBeNull()
  if (box === null) return
  expect(box.x).toBeGreaterThanOrEqual(0)
  expect(box.x + box.width).toBeLessThanOrEqual(390)
  expect(box.y + box.height).toBeLessThanOrEqual(844)
  await page.screenshot({ path: resolve(evidence, 'settings-mobile.png') })
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(dialog).not.toBeVisible()
})
