/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtworkRouteImport } from './routes/artwork'
import { Route as ProbeCapabilitiesRouteImport } from './routes/[_]probe.capabilities'
import { Route as ProbeCompositeRouteImport } from './routes/[_]probe.composite'
import { Route as SpikeDeviceRouteImport } from './routes/[_]spike.device'
import { Route as ApiStickersRouteImport } from './routes/api.stickers'
import { Route as ApiAppleDeveloperTokenRouteImport } from './routes/api.apple.developer-token'
import { Route as ApiStickersDeviceRouteImport } from './routes/api.stickers.device'
import { Route as ApiStickersListeningRouteImport } from './routes/api.stickers.listening'
import { Route as ApiStickersPlacementsRouteImport } from './routes/api.stickers.placements'
import { Route as ApiStickersSessionRouteImport } from './routes/api.stickers.session'
import { Route as ApiStickersPacksOpenRouteImport } from './routes/api.stickers.packs.open'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworkRoute = ArtworkRouteImport.update({
  id: '/artwork',
  path: '/artwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeCapabilitiesRoute = ProbeCapabilitiesRouteImport.update({
  id: '/_probe/capabilities',
  path: '/_probe/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProbeCompositeRoute = ProbeCompositeRouteImport.update({
  id: '/_probe/composite',
  path: '/_probe/composite',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeDeviceRoute = SpikeDeviceRouteImport.update({
  id: '/_spike/device',
  path: '/_spike/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStickersRoute = ApiStickersRouteImport.update({
  id: '/api/stickers',
  path: '/api/stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppleDeveloperTokenRoute = ApiAppleDeveloperTokenRouteImport.update({
  id: '/api/apple/developer-token',
  path: '/api/apple/developer-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStickersDeviceRoute = ApiStickersDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => ApiStickersRoute,
} as any)
const ApiStickersListeningRoute = ApiStickersListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => ApiStickersRoute,
} as any)
const ApiStickersPlacementsRoute = ApiStickersPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => ApiStickersRoute,
} as any)
const ApiStickersSessionRoute = ApiStickersSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiStickersRoute,
} as any)
const ApiStickersPacksOpenRoute = ApiStickersPacksOpenRouteImport.update({
  id: '/packs/open',
  path: '/packs/open',
  getParentRoute: () => ApiStickersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artwork': typeof ArtworkRoute
  '/_probe/capabilities': typeof ProbeCapabilitiesRoute
  '/_probe/composite': typeof ProbeCompositeRoute
  '/_spike/device': typeof SpikeDeviceRoute
  '/api/stickers': typeof ApiStickersRouteWithChildren
  '/api/apple/developer-token': typeof ApiAppleDeveloperTokenRoute
  '/api/stickers/device': typeof ApiStickersDeviceRoute
  '/api/stickers/listening': typeof ApiStickersListeningRoute
  '/api/stickers/placements': typeof ApiStickersPlacementsRoute
  '/api/stickers/session': typeof ApiStickersSessionRoute
  '/api/stickers/packs/open': typeof ApiStickersPacksOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artwork': typeof ArtworkRoute
  '/_probe/capabilities': typeof ProbeCapabilitiesRoute
  '/_probe/composite': typeof ProbeCompositeRoute
  '/_spike/device': typeof SpikeDeviceRoute
  '/api/stickers': typeof ApiStickersRouteWithChildren
  '/api/apple/developer-token': typeof ApiAppleDeveloperTokenRoute
  '/api/stickers/device': typeof ApiStickersDeviceRoute
  '/api/stickers/listening': typeof ApiStickersListeningRoute
  '/api/stickers/placements': typeof ApiStickersPlacementsRoute
  '/api/stickers/session': typeof ApiStickersSessionRoute
  '/api/stickers/packs/open': typeof ApiStickersPacksOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artwork': typeof ArtworkRoute
  '/_probe/capabilities': typeof ProbeCapabilitiesRoute
  '/_probe/composite': typeof ProbeCompositeRoute
  '/_spike/device': typeof SpikeDeviceRoute
  '/api/stickers': typeof ApiStickersRouteWithChildren
  '/api/apple/developer-token': typeof ApiAppleDeveloperTokenRoute
  '/api/stickers/device': typeof ApiStickersDeviceRoute
  '/api/stickers/listening': typeof ApiStickersListeningRoute
  '/api/stickers/placements': typeof ApiStickersPlacementsRoute
  '/api/stickers/session': typeof ApiStickersSessionRoute
  '/api/stickers/packs/open': typeof ApiStickersPacksOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artwork'
    | '/_probe/capabilities'
    | '/_probe/composite'
    | '/_spike/device'
    | '/api/stickers'
    | '/api/apple/developer-token'
    | '/api/stickers/device'
    | '/api/stickers/listening'
    | '/api/stickers/placements'
    | '/api/stickers/session'
    | '/api/stickers/packs/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artwork'
    | '/_probe/capabilities'
    | '/_probe/composite'
    | '/_spike/device'
    | '/api/stickers'
    | '/api/apple/developer-token'
    | '/api/stickers/device'
    | '/api/stickers/listening'
    | '/api/stickers/placements'
    | '/api/stickers/session'
    | '/api/stickers/packs/open'
  id:
    | '__root__'
    | '/'
    | '/artwork'
    | '/_probe/capabilities'
    | '/_probe/composite'
    | '/_spike/device'
    | '/api/stickers'
    | '/api/apple/developer-token'
    | '/api/stickers/device'
    | '/api/stickers/listening'
    | '/api/stickers/placements'
    | '/api/stickers/session'
    | '/api/stickers/packs/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtworkRoute: typeof ArtworkRoute
  ProbeCapabilitiesRoute: typeof ProbeCapabilitiesRoute
  ProbeCompositeRoute: typeof ProbeCompositeRoute
  SpikeDeviceRoute: typeof SpikeDeviceRoute
  ApiStickersRoute: typeof ApiStickersRouteWithChildren
  ApiAppleDeveloperTokenRoute: typeof ApiAppleDeveloperTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artwork': {
      id: '/artwork'
      path: '/artwork'
      fullPath: '/artwork'
      preLoaderRoute: typeof ArtworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_probe/capabilities': {
      id: '/_probe/capabilities'
      path: '/_probe/capabilities'
      fullPath: '/_probe/capabilities'
      preLoaderRoute: typeof ProbeCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_probe/composite': {
      id: '/_probe/composite'
      path: '/_probe/composite'
      fullPath: '/_probe/composite'
      preLoaderRoute: typeof ProbeCompositeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_spike/device': {
      id: '/_spike/device'
      path: '/_spike/device'
      fullPath: '/_spike/device'
      preLoaderRoute: typeof SpikeDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stickers': {
      id: '/api/stickers'
      path: '/api/stickers'
      fullPath: '/api/stickers'
      preLoaderRoute: typeof ApiStickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apple/developer-token': {
      id: '/api/apple/developer-token'
      path: '/api/apple/developer-token'
      fullPath: '/api/apple/developer-token'
      preLoaderRoute: typeof ApiAppleDeveloperTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stickers/device': {
      id: '/api/stickers/device'
      path: '/device'
      fullPath: '/api/stickers/device'
      preLoaderRoute: typeof ApiStickersDeviceRouteImport
      parentRoute: typeof ApiStickersRoute
    }
    '/api/stickers/listening': {
      id: '/api/stickers/listening'
      path: '/listening'
      fullPath: '/api/stickers/listening'
      preLoaderRoute: typeof ApiStickersListeningRouteImport
      parentRoute: typeof ApiStickersRoute
    }
    '/api/stickers/placements': {
      id: '/api/stickers/placements'
      path: '/placements'
      fullPath: '/api/stickers/placements'
      preLoaderRoute: typeof ApiStickersPlacementsRouteImport
      parentRoute: typeof ApiStickersRoute
    }
    '/api/stickers/session': {
      id: '/api/stickers/session'
      path: '/session'
      fullPath: '/api/stickers/session'
      preLoaderRoute: typeof ApiStickersSessionRouteImport
      parentRoute: typeof ApiStickersRoute
    }
    '/api/stickers/packs/open': {
      id: '/api/stickers/packs/open'
      path: '/packs/open'
      fullPath: '/api/stickers/packs/open'
      preLoaderRoute: typeof ApiStickersPacksOpenRouteImport
      parentRoute: typeof ApiStickersRoute
    }
  }
}

interface ApiStickersRouteChildren {
  ApiStickersDeviceRoute: typeof ApiStickersDeviceRoute
  ApiStickersListeningRoute: typeof ApiStickersListeningRoute
  ApiStickersPlacementsRoute: typeof ApiStickersPlacementsRoute
  ApiStickersSessionRoute: typeof ApiStickersSessionRoute
  ApiStickersPacksOpenRoute: typeof ApiStickersPacksOpenRoute
}

const ApiStickersRouteChildren: ApiStickersRouteChildren = {
  ApiStickersDeviceRoute: ApiStickersDeviceRoute,
  ApiStickersListeningRoute: ApiStickersListeningRoute,
  ApiStickersPlacementsRoute: ApiStickersPlacementsRoute,
  ApiStickersSessionRoute: ApiStickersSessionRoute,
  ApiStickersPacksOpenRoute: ApiStickersPacksOpenRoute,
}

const ApiStickersRouteWithChildren = ApiStickersRoute._addFileChildren(
  ApiStickersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtworkRoute: ArtworkRoute,
  ProbeCapabilitiesRoute: ProbeCapabilitiesRoute,
  ProbeCompositeRoute: ProbeCompositeRoute,
  SpikeDeviceRoute: SpikeDeviceRoute,
  ApiStickersRoute: ApiStickersRouteWithChildren,
  ApiAppleDeveloperTokenRoute: ApiAppleDeveloperTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
