import {BoxGeometry,Matrix4,PerspectiveCamera,Vector3} from '../../../../../../packages/device/node_modules/three';
import {createStickerCollision} from '../../../../../../packages/device/src/sticker-collision';
import {createCarryPreparation} from '../../../../../../packages/device/src/sticker-carry-preparation';
import {createCarryWearCache} from '../../../../../../packages/device/src/sticker-carry-wear';
import {transferPaperGeometry} from '../../../../../../packages/device/src/sticker-paper-transfer';
import {bindStickerWrapSurface,createStickerWrapSurface} from '../../../../../../packages/device/src/sticker-wrap';
import {DEFAULT_DEVICE_FORM} from '../../../../../../packages/device/src/form';
import type {CarryInput} from '../../../../../../packages/device/src/sticker-carry-computation';
const assert=(condition:unknown,message:string)=>{if(!condition)throw Error(message)};
const until=async(check:()=>boolean)=>{for(let i=0;i<400;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,5))}throw Error('deadline')};
const rear=new BoxGeometry(330,550,50);rear.computeBoundingSphere();bindStickerWrapSurface(rear,createStickerWrapSurface(DEFAULT_DEVICE_FORM,[]));
const collision=createStickerCollision([{geometry:rear,source:'box',kind:'surface'}]);
const snapshot=collision.snapshot();assert(collision.snapshot().root===snapshot.root,'built snapshot not cached');
const restored=createStickerCollision([],{...snapshot,metadata:snapshot.metadata.map(value=>({...value}))});
assert(restored.snapshot().root===snapshot.root,'prepared snapshot reserialized');
assert(restored.snapshot().root===restored.snapshot().root,'restored root not stable');
const start=new Vector3(0,0,-100),end=new Vector3(0,0,100);assert(JSON.stringify(restored.castSegment(start,end))===JSON.stringify(collision.castSegment(start,end)),'query parity');
restored.dispose();let rejected=false;try{restored.snapshot()}catch{rejected=true}assert(rejected,'disposed snapshot admitted');assert(collision.snapshot().metadata.length===1,'borrowed metadata corrupted');
// Leases keep a displayed resource live after cache replacement/worker stop.
const cache=createCarryWearCache();cache.accept(1,transferPaperGeometry(rear));const lease=cache.retain();let released=0;lease.geometry?.addEventListener('dispose',()=>released++);cache.accept(1,undefined);const second=cache.retain();assert(lease.geometry===second.geometry,'identity changed');cache.clear();assert(released===0,'cache clear disposed displayed wear');lease.release();second.release();second.release();assert(released===1,'lease disposal count');
let missing=false;try{cache.accept(2,undefined)}catch{missing=true}assert(missing,'missing revision payload accepted');
const documentMock=Object.assign(new EventTarget(),{hidden:false});Object.defineProperty(globalThis,'document',{value:documentMock,configurable:true});
const camera=new PerspectiveCamera(40,440/956,1,3000);camera.position.set(0,0,-1000);camera.lookAt(0,0,0);camera.updateMatrixWorld();
const art={id:'resource-parity',url:'',width:100,height:180,visibleBounds:[0,0,100,180] as const};
const placement={stickerId:art.id,surface:'back' as const,x:.8,y:.22,width:.2,rotationDeg:23};
const input:CarryInput={art,pack:{progress:1,stickerId:art.id,sourcePlacement:placement,peel:.3,sourcePeelFront:.3,landing:0,placement:null,computationEpoch:1},width:66,paperWidth:300,pixel:1,seatX:.5,origin:[0,-140,132],world:new Matrix4().toArray(),cameraWorld:camera.matrixWorld.toArray(),projection:camera.projectionMatrix.toArray(),viewportWidth:440,viewportHeight:956,worldPixel:1,workspaceBounds:null};
const visibility={ready:true,revision:1,snapshot:()=>collision.snapshot()};const runtime=createCarryPreparation(),unmount=runtime.mount();
runtime.request(input,rear,visibility);const current={...input,pack:{...input.pack,computationEpoch:2,peel:.4}};runtime.request(current,rear,visibility);
await until(()=>runtime.getSnapshot().frame?.input.pack.computationEpoch===2);
const firstWear=runtime.getSnapshot().frame?.wearGeometry;assert(firstWear,'wear missing after discarded first epoch');let oldDisposals=0;firstWear?.addEventListener('dispose',()=>oldDisposals++);
runtime.request({...current,pack:{...current.pack,peel:.5}},rear,visibility);await until(()=>runtime.getSnapshot().frame?.input.pack.peel===.5);assert(runtime.getSnapshot().frame?.wearGeometry===firstWear,'worker frame wear changed');runtime.commit();assert(oldDisposals===0,'retired frame disposed shared live wear');
runtime.request({...current,pack:{...current.pack,peel:.6,sourcePlacement:{...placement,x:.7}}},rear,visibility);await until(()=>runtime.getSnapshot().frame?.input.pack.peel===.6);assert(runtime.getSnapshot().frame?.wearGeometry!==firstWear,'changed source reused wrong wear');assert(oldDisposals===0,'old display freed before commit');runtime.commit();assert(oldDisposals===1,'old resource not released');
const finalWear=runtime.getSnapshot().frame?.wearGeometry;let finalDisposals=0;finalWear?.addEventListener('dispose',()=>finalDisposals++);unmount();assert(finalDisposals===1,'unmount resource disposal');
rear.dispose();collision.dispose();console.log(JSON.stringify({builtSnapshotCached:true,preparedRootReused:true,queryParity:true,disposedRejected:true,metadataPreserved:true,leaseIdentityAndDisposal:true,discardedEpochPayloadRetained:true,workerFramesReuseWear:true,changedSourceReplacesWear:true,commitAndUnmountOwnership:true}));
