import {Vector3,BufferGeometry,Float32BufferAttribute} from '/Users/vinicius/code/webPod/node_modules/.bun/three@0.185.1/node_modules/three/build/three.module.js';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {stickerSheetTriangleMetric} from '/Users/vinicius/code/webPod/packages/device/src/sticker-sheet-metric';
import {ExtrudeGeometry} from '/Users/vinicius/code/webPod/node_modules/.bun/three@0.185.1/node_modules/three/build/three.module.js';
import {createStickerCollision} from '/Users/vinicius/code/webPod/packages/device/src/sticker-collision';
import {createRearShellGeometry,frontShellPlan,productShellDepths} from '/Users/vinicius/code/webPod/packages/device/src/product-shell';
import {silhouetteShape} from '/Users/vinicius/code/webPod/packages/device/src/shapes';
import {DEFAULT_DEVICE_FORM as f} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {DEVICE_LAYOUT} from '/Users/vinicius/code/webPod/packages/device/src/layout';
const b=DEVICE_LAYOUT.body;const rear=createRearShellGeometry({width:b.width,height:b.height,depth:b.depth,cornerR:b.cornerR,exponent:b.exponent,frontThickness:f.frontThickness,rearCrownInset:f.rearCrownInset,frontRimInset:f.seamWidth+f.frontBevel+.25});
const plan=frontShellPlan(b.width,b.height,b.cornerR,f.seamWidth,f.frontBevel),front=new ExtrudeGeometry(silhouetteShape(plan.faceWidth,plan.faceHeight,plan.faceCornerR,2,48),{depth:f.frontThickness-2*f.frontBevel,bevelEnabled:true,bevelThickness:f.frontBevel,bevelSize:f.frontBevel,bevelSegments:16,steps:1});front.translate(0,0,productShellDepths(b.depth,f.frontThickness).seamZ+f.frontBevel);

// Nominal unobstructed front fixture: explicitly remove its hidden rear cap.
const source=front.getAttribute('position'),out=[];for(let i=0;i<source.count;i+=3){const a=new Vector3().fromBufferAttribute(source,i),b=new Vector3().fromBufferAttribute(source,i+1),c=new Vector3().fromBufferAttribute(source,i+2);if(b.clone().sub(a).cross(c.clone().sub(a)).normalize().z<-.9999)continue;out.push(...a.toArray(),...b.toArray(),...c.toArray());}const outside=new BufferGeometry();outside.setAttribute('position',new Float32BufferAttribute(out,3));
const collider=createStickerCollision([{geometry:rear,source:'source rear before ports',kind:'surface',adhesiveSupport:true},{geometry:outside,source:'unobstructed nominal front exterior',kind:'surface',adhesiveSupport:true}]);
const wrap=createStickerWrapSurface(f,[{geometry:front}]);
const data=await Bun.file("/Users/vinicius/code/webPod/docs/workstreams/015-listening-sticker-collection/evidence/sticker-edge-wrap/early/c03-sheet-probe.json").json();const rest=data.rest,ps=data.positions.map(p=>new Vector3(...p)),n=16,result=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){const a=y*(n+1)+x;for(const ids of [[a,a+1,a+n+1],[a+n+2,a+n+1,a+1]]){const m=stickerSheetTriangleMetric(ids.map(i=>rest[i]),ids.map(i=>ps[i]));const center=ids.reduce((p,i)=>p.add(ps[i]),new Vector3()).multiplyScalar(1/3);const hit=collider.closestApprovedSupport(center,30);result.push({ids,rest:ids.map(i=>rest[i]),points:ids.map(i=>ps[i].toArray()),min:m?.minimumStretch,max:m?.maximumStretch,area:m?.areaRatio,intersection:collider.intersectsTriangle(...ids.map(i=>ps[i])),support:hit?.source,gap:hit?.signedDistance,normalDot:m?.normal.clone().normalize().dot(hit?.normal??new Vector3())});}}result.sort((a,b)=>a.min-b.min);console.log(JSON.stringify({minimum:result.slice(0,6),intersections:result.filter(x=>x.intersection)}));collider.dispose();outside.dispose();rear.dispose();front.dispose();