import assert from 'node:assert/strict';
import {GlobalRegistrator} from '../../../../../../packages/composite/node_modules/@happy-dom/global-registrator';
import {Matrix4,PerspectiveCamera,Vector3} from '../../../../../../packages/device/node_modules/three';
import {prepareDeviceSteps,restorePreparedDevice,disposePreparedDevice} from '../../../../../../packages/device/src/device-preparation-data';
import {drainSteps} from '../../../../../../packages/device/src/sticker-computation-steps';
import {DEFAULT_DEVICE_FORM as form} from '../../../../../../packages/device/src/form';
import {DEFAULT_DEVICE_MATERIALS as materials} from '../../../../../../packages/device/src/materials';
import {createDeviceQueryView} from '../../../../../../packages/device/src/device-query-view';
import {createDeviceNativeInput} from '../../../../../../packages/device/src/device-native-input';
import type {DeviceMotionBinding} from '../../../../../../packages/device/src/device-motion-authority';
import type {RenderPose,RenderControlResponse,RenderCommand} from '../../../../../../packages/device/src/device-render-protocol';
import {DEVICE_LAYOUT} from '../../../../../../packages/device/src/layout';
GlobalRegistrator.register();
const data=restorePreparedDevice(drainSteps(prepareDeviceSteps(form))),query=createDeviceQueryView(data,form,materials);
const canvas=document.createElement('canvas');canvas.setAttribute('role','application');document.body.append(canvas);
const camera=new PerspectiveCamera(30,440/956,.1,5000);camera.position.z=1500;camera.updateMatrixWorld(true);
const layout={revision:1,cssWidth:440,cssHeight:956,backingWidth:1320,backingHeight:2868,pixelRatio:3,cameraWorld:camera.matrixWorld.toArray(),cameraProjection:camera.projectionMatrix.toArray()};
let pose:RenderPose={sequence:0,motionEpoch:1,lastAcceptedCommand:0,layoutRevision:1,sceneRevision:1,resourceRevision:1,orientation:{pitchDeg:0,yawDeg:0,rollDeg:0},reveal:null,nodes:[{id:'device-model',matrix:new Matrix4().toArray()},{id:'wheel-assembly',matrix:query.wheel.matrix.toArray()},{id:'select',matrix:query.select.matrix.toArray()}]},sequence=0;
const listeners=new Set<(response:RenderControlResponse)=>void>(),commands:RenderCommand[]=[];
const binding:DeviceMotionBinding={read:()=>pose,nextCommandSequence:()=>++sequence,sendPose(next){pose=next;},sendCommand(command){commands.push(command);pose=command.pose;},subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);}};
const captured=new Set<number>();
canvas.setPointerCapture=id=>{captured.add(id);};canvas.hasPointerCapture=id=>captured.has(id);canvas.releasePointerCapture=id=>{captured.delete(id);};
canvas.getBoundingClientRect=()=>new DOMRect(0,0,440,956);
let picks=0, accepted=true, attempts=0, endDuringAdmission=false, failCapture=false;
const originalFront=query.front.raycast,originalRear=query.rear.raycast;
query.front.raycast=function(...args){picks++;return originalFront.apply(this,args);};
query.rear.raycast=function(...args){picks++;return originalRear.apply(this,args);};
const dispose=createDeviceNativeInput({canvas,query,form,binding,layout:()=>layout,callbacks:()=>({}),onOrientationGrabStart:start=>{
 attempts++;if(!accepted)return false;if(!failCapture)start.capture.setPointerCapture(start.pointerId);
 if(endDuringAdmission)canvas.dispatchEvent(new PointerEvent('pointercancel',{pointerId:start.pointerId}));return true;
}});
const point=(x:number,y:number)=>{query.content.updateWorldMatrix(true,true);return new Vector3(x,y,0).applyMatrix4(query.front.matrixWorld).project(camera);};
const edge=point(DEVICE_LAYOUT.body.width/2-1,0),wheel=point(DEVICE_LAYOUT.wheel.centerX+DEVICE_LAYOUT.wheel.outerR*.8,DEVICE_LAYOUT.wheel.centerY);
const fire=(type:string,id=1,p=edge,primary=true)=>canvas.dispatchEvent(new PointerEvent(type,{pointerId:id,pointerType:'touch',isPrimary:primary,button:0,clientX:(p.x+1)*220,clientY:(1-p.y)*478,bubbles:true}));
const checks:Record<string,boolean>={};
const check=(name:string,condition:boolean)=>{assert(condition,name);checks[name]=true;};
fire('pointerdown');check('exactDownAccepted',attempts===1&&captured.has(1)&&picks>0);
let before=picks;for(let n=0;n<24;n++)fire('pointermove');check('capturedMovesZeroHoverPicks',picks===before);
accepted=false;fire('pointerdown',2,edge);accepted=true;before=picks;fire('pointermove');check('declinedSecondDownPreservesOwner',picks===before);fire('pointercancel',2);fire('pointermove');check('otherPointerCancelPreservesOwner',picks===before);
fire('pointermove',2,edge);check('otherPrimaryPointerStillPicks',picks>before);
before=picks;fire('pointermove',2,edge,false);check('nonprimaryStillRejected',picks===before);
fire('pointerup');before=picks;fire('pointermove');check('upRestoresHover',picks>before);
for(const terminal of ['pointercancel','lostpointercapture','blur']){
 fire('pointerdown');before=picks;if(terminal==='blur')window.dispatchEvent(new Event('blur'));else fire(terminal);
 fire('pointermove');check(`${terminal}RestoresHover`,picks>before);
}
captured.add(99);before=picks;fire('pointermove',99);check('unrelatedCaptureDoesNotSuppressHover',picks>before);
accepted=false;fire('pointerdown');before=picks;fire('pointermove');check('declinedAdmissionStillHovers',picks>before);accepted=true;
captured.clear();failCapture=true;fire('pointerdown');before=picks;fire('pointermove');check('acceptedWithoutCaptureStillHovers',picks>before);failCapture=false;
endDuringAdmission=true;fire('pointerdown');before=picks;fire('pointermove');check('reentrantCancelCannotInstallOwner',picks>before);endDuringAdmission=false;
fire('pointerdown');captured.clear();before=picks;fire('pointermove');check('missingCaptureRestoresHoverBeforeLostEvent',picks>before);
const attemptBefore=attempts;fire('pointerdown',4,new Vector3(4,4,0));check('outsideDoesNotAdmit',attempts===attemptBefore);
fire('pointerdown',5,wheel);check('wheelNeverBecomesOrientationOwner',attempts===attemptBefore);before=picks;fire('pointermove',5,wheel);check('wheelMoveKeepsSharedControlPath',picks===before);fire('pointerup',5,wheel);
pose={...pose,orientation:{pitchDeg:0,yawDeg:180,rollDeg:0},nodes:pose.nodes.map(n=>n.id==='device-model'?{...n,matrix:new Matrix4().makeRotationY(Math.PI).toArray()}:n)};query.applyPose(pose);
const rearEdge=point(DEVICE_LAYOUT.body.width/2-1,0);fire('pointerdown',6,rearEdge);before=picks;fire('pointermove',6,rearEdge);check('rearCaptureSuppressesOnlyHover',picks===before);fire('pointercancel',6,rearEdge);
fire('pointerdown',7,rearEdge);before=picks;dispose();dispose();fire('pointermove',7,rearEdge);fire('pointerdown',8,rearEdge);window.dispatchEvent(new Event('blur'));check('disposedListenersPerformZeroPicks',picks===before);check('cursorCleared',canvas.dataset['wpCursorControl']===undefined);check('bindingListenersReleased',listeners.size===0);
query.dispose();disposePreparedDevice(data);canvas.remove();GlobalRegistrator.unregister();
const result={kind:'Actual native adapter and query geometry, controlled Happy DOM pointer capture, not trusted browser performance',checks,picks,attempts};await Bun.write(new URL('./ownership.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(result);
