import {Matrix4,Vector3,Mesh,MeshBasicMaterial,Raycaster,FrontSide} from '/Users/vinicius/code/webPod/packages/device/node_modules/three';
import {actualShell} from '../wrapped-witness-4/source-shell';
import {createStickerWrapSurface} from '/Users/vinicius/code/webPod/packages/device/src/sticker-wrap';
import {createStickerSurfaceGeometry} from '/Users/vinicius/code/webPod/packages/device/src/sticker-surface';
import {DEFAULT_DEVICE_FORM} from '/Users/vinicius/code/webPod/packages/device/src/form';
import {getSticker} from '/Users/vinicius/code/webPod/packages/stickers/src/catalogue';
const shell=actualShell(),faces=shell.faces.filter(f=>f.source!=='top cap and outer bevel candidate support'&&!f.source.includes('rear')).map(f=>({geometry:f.geometry,offset:f.transform?[f.transform.elements[12],f.transform.elements[13],f.transform.elements[14]]:undefined})),wrap=createStickerWrapSurface(DEFAULT_DEVICE_FORM,faces),art=getSticker('PW-C03')!,placement={stickerId:art.id,surface:'back' as const,x:.027,y:.017,width:.35,rotationDeg:0,wear:1},g=createStickerSurfaceGeometry(art,placement,shell.rear,wrap),p=g.getAttribute('position'),mesh=new Mesh(g,new MeshBasicMaterial({side:FrontSide}));mesh.updateMatrixWorld();
const old=await Bun.file(import.meta.dir+'/../wrapped-witness-5/candidates.json').json(),capture=await Bun.file(old.results[0].capturePath).json(),raw=capture.submitted.candidates[0].rawBuffers.find(b=>b.role==='position'),oldp=new Float32Array(new Uint8Array(raw.bytes).buffer);let maxDelta=0,changed=0;for(let i=0;i<p.count;i++){const d=Math.hypot(p.getX(i)-oldp[i*3],p.getY(i)-oldp[i*3+1],p.getZ(i)-oldp[i*3+2]);maxDelta=Math.max(maxDelta,d);if(d>1e-4)changed++;}
const results=[];for(const r of old.results){const world=new Matrix4().fromArray(r.matrices.contentWorld),view=new Matrix4().fromArray(r.matrices.cameraWorld).invert(),project=new Matrix4().fromArray(r.matrices.cameraProjection),inverse=project.multiply(view).multiply(world).invert(),q=r.chosen.pickup.point,ndc={x:2*(q.x-r.rect.left)/r.rect.width-1,y:1-2*(q.y-r.rect.top)/r.rect.height},near=new Vector3(ndc.x,ndc.y,-1).applyMatrix4(inverse),far=new Vector3(ndc.x,ndc.y,1).applyMatrix4(inverse),ray=new Raycaster(near,far.sub(near).normalize()),hit=ray.intersectObject(mesh,false)[0];results.push({name:r.viewport.width+'-'+r.face,oldUV:r.chosen.pickup.uv,newUV:hit?.uv?.toArray(),delta:hit?.uv?Math.hypot(hit.uv.x-r.chosen.pickup.uv[0],hit.uv.y-r.chosen.pickup.uv[1]):null});}
const output={maxVertexDelta:maxDelta,changedVerticesOver1e4:changed,total:p.count,results};console.log(output);await Bun.write(import.meta.dir+'/pickup-correspondence.json',JSON.stringify(output,null,2));mesh.material.dispose();g.dispose();shell.dispose();
