import { strict as assert } from 'node:assert';
import { Group, Mesh, MeshBasicMaterial, PlaneGeometry } from '../../../../../../packages/device/node_modules/three/build/three.module.js';
import { MeshBasicNodeMaterial } from '../../../../../../packages/device/node_modules/three/build/three.webgpu.js';
import { vec4 } from '../../../../../../packages/device/node_modules/three/build/three.tsl.js';
import { installNativeMaterialOutput, assertNativeMaterialOutput } from '../../../../../../packages/device/src/native-material-output';
const material = new MeshBasicNodeMaterial();
material.customProgramCacheKey = function () { assert.equal(this, material); return 'original-key'; };
const original = material.setupOutput;
installNativeMaterialOutput(material);
const first = material.setupOutput, version = material.version;
assert.notEqual(first, original); assert.match(material.customProgramCacheKey(), /^original-key\|webpod-gl-fragment-output-v1\|mapped$/);
installNativeMaterialOutput(material); assert.equal(material.setupOutput, first); assert.equal(material.version, version);
material.toneMapped = false; assert.match(material.customProgramCacheKey(), /unmapped$/);
const geometry = new PlaneGeometry(), root = new Group(); root.add(new Mesh(geometry, material)); assertNativeMaterialOutput(root);
const unsupported = new MeshBasicNodeMaterial(); unsupported.outputNode = vec4(1); assert.throws(() => installNativeMaterialOutput(unsupported));
const stock = new MeshBasicMaterial(); assert.throws(() => installNativeMaterialOutput(stock));
material.outputNode = vec4(1); assert.throws(() => assertNativeMaterialOutput(root)); material.outputNode = null;
const raw = new MeshBasicNodeMaterial(); root.add(new Mesh(geometry, raw)); assert.throws(() => assertNativeMaterialOutput(root));
for (const m of [material, unsupported, stock, raw]) m.dispose(); geometry.dispose();
const result = { checks: 10, idempotent: true, originalCacheReceiver: true, toneMappedCacheIdentity: true, detachedCoverage: true, unsupportedOutputAndStockRejected: true, mutatedOutputRejectedBeforeAdmission: true, gpuPixelParity: 'separate lead-owned probe required' };
await Bun.write(new URL('./contracts.json', import.meta.url), JSON.stringify(result, null, 2) + '\n'); console.log(JSON.stringify(result));
