import assert from 'node:assert/strict';
import {GlobalRegistrator} from '../../../../../../packages/composite/node_modules/@happy-dom/global-registrator';
import {Matrix4,PerspectiveCamera} from '../../../../../../packages/device/node_modules/three';
import {prepareDeviceSteps,restorePreparedDevice,disposePreparedDevice} from '../../../../../../packages/device/src/device-preparation-data';
import {drainSteps} from '../../../../../../packages/device/src/sticker-computation-steps';
import {DEFAULT_DEVICE_FORM as form} from '../../../../../../packages/device/src/form';
import {DEFAULT_DEVICE_MATERIALS as materials} from '../../../../../../packages/device/src/materials';
import {createDeviceQueryView} from '../../../../../../packages/device/src/device-query-view';
import {createDeviceNativeInput} from '../../../../../../packages/device/src/device-native-input';
import type {DeviceMotionBinding} from '../../../../../../packages/device/src/device-motion-authority';
import type {RenderPose,RenderControlResponse,RenderCommand} from '../../../../../../packages/device/src/device-render-protocol';
GlobalRegistrator.register();
const data=restorePreparedDevice(drainSteps(prepareDeviceSteps(form))),query=createDeviceQueryView(data,form,materials);
const canvas=document.createElement('canvas');canvas.setAttribute('role','application');document.body.append(canvas);
const camera=new PerspectiveCamera(30,440/956,.1,5000);camera.position.z=1500;camera.updateMatrixWorld(true);
const layout={revision:1,cssWidth:440,cssHeight:956,backingWidth:1320,backingHeight:2868,pixelRatio:3,cameraWorld:camera.matrixWorld.toArray(),cameraProjection:camera.projectionMatrix.toArray()};
let pose:RenderPose={sequence:0,motionEpoch:1,lastAcceptedCommand:0,layoutRevision:1,sceneRevision:1,resourceRevision:1,orientation:{pitchDeg:0,yawDeg:0,rollDeg:0},reveal:null,nodes:[{id:'device-model',matrix:new Matrix4().toArray()},{id:'wheel-assembly',matrix:query.wheel.matrix.toArray()},{id:'select',matrix:query.select.matrix.toArray()}]},sequence=0;
const listeners=new Set<(response:RenderControlResponse)=>void>(),commands:RenderCommand[]=[];
const binding:DeviceMotionBinding={read:()=>pose,nextCommandSequence:()=>++sequence,sendPose(next){pose=next;},sendCommand(command){commands.push(command);pose=command.pose;},subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);}};
const dispose=createDeviceNativeInput({canvas,query,form,binding,layout:()=>layout,callbacks:()=>({})});
const key=(type:'keydown'|'keyup')=>canvas.dispatchEvent(new KeyboardEvent(type,{key:'Enter',bubbles:true}));
key('keydown');assert(commands.some(command=>command.kind==='control-down'));
const notify=()=>{const response:RenderControlResponse={type:'projection',version:1,epoch:1,projection:{notificationSequence:1,epoch:1,sceneRevision:1,resourceRevision:1,layoutRevision:1,pose,screenWorld:new Matrix4().toArray(),screenWidth:272,screenHeight:204,cameraWorld:layout.cameraWorld,cameraProjection:layout.cameraProjection}};for(const listener of [...listeners])listener(response);};
pose={...pose,orientation:{pitchDeg:0,yawDeg:180,rollDeg:0}};notify();const afterRear=commands.length;key('keydown');key('keyup');assert.equal(commands.length,afterRear);
pose={...pose,orientation:{pitchDeg:0,yawDeg:0,rollDeg:0}};notify();key('keydown');assert(commands.length>afterRear);key('keyup');
canvas.dataset['wpCursorControl']='true';canvas.dispatchEvent(new Event('pointerleave'));assert.equal(canvas.dataset['wpCursorControl'],undefined);
dispose();dispose();assert.equal(listeners.size,0);const afterDispose=commands.length;key('keydown');assert.equal(commands.length,afterDispose);assert.equal(canvas.dataset['wpCursorControl'],undefined);
query.dispose();disposePreparedDevice(data);canvas.remove();GlobalRegistrator.unregister();
const result={kind:'Actual native input adapter with controlled Happy DOM events, not trusted browser activation',checks:{frontEnterAdmitted:true,rearEnterSuppressed:true,frontReadmissionWorks:true,pointerLeaveClearsCursor:true,disposalRemovesMotionAndKeyboardListeners:true}};
await Bun.write(new URL('./native-input-gates.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(result);
