import assert from 'node:assert/strict';
import {Texture} from '../../../../../../packages/device/node_modules/three/build/three.module.js';
import {prepareStickerPackRenderFrame} from '../../../../../../packages/device/src/sticker-pack-render-frame';
import {prepareStickerPackGeometry} from '../../../../../../packages/device/src/sticker-pack-resource-data';
import {drainSteps} from '../../../../../../packages/device/src/sticker-computation-steps';
import {stickerPackGeometryKey} from '../../../../../../packages/device/src/sticker-pack-recipe';
const recipe={kind:'group' as const,id:'root',children:[]};
const input={kind:'plane' as const,width:2,height:3};
const key=stickerPackGeometryKey(input),geometry=new MessageChannel(),damage=new MessageChannel();
let closes=0;
const texture=new Texture();
const bitmap={image:{width:2,height:2,close(){closes++;}},colorSpace:texture.colorSpace,wrapS:texture.wrapS,wrapT:texture.wrapT,minFilter:texture.minFilter,magFilter:texture.magFilter,generateMipmaps:true,anisotropy:1};
const firstPending=prepareStickerPackRenderFrame({key:'first',recipe,geometry:[{key,id:1,port:geometry.port2}],damage:[{id:2,port:damage.port2}],artworks:[{id:'art',bitmap}],prints:[]},null,new AbortController().signal);
geometry.port1.postMessage({version:1,id:1,value:drainSteps(prepareStickerPackGeometry(input))});
damage.port1.postMessage({version:1,id:2,result:{kind:'render-damage',stickerId:'art',width:2,height:2,gpu:new Uint8Array([0,1,2,255])}});
const first=await firstPending;
const reuse={geometry:[{key,id:1}],damage:[2],artworks:['art']};
const wire={key:'candidate',recipe,geometry:[],damage:[],artworks:[],prints:[],reuse};
const originalGeometry=first.resources.geometry.get(key)?.unit.value['geometry'];
const originalDamage=first.resources.damage.get(2)?.value.texture;
const originalArtwork=first.resources.artwork.get('art')?.value;
assert(originalGeometry&&originalDamage&&originalArtwork);
let geometryDisposes=0,damageDisposes=0,artDisposes=0;
originalGeometry.addEventListener('dispose',()=>geometryDisposes++);originalDamage.addEventListener('dispose',()=>damageDisposes++);originalArtwork.addEventListener('dispose',()=>artDisposes++);
const candidate=await prepareStickerPackRenderFrame(wire,null,new AbortController().signal,first.resources);
assert.equal(candidate.resources.geometry.get(key)?.unit.value['geometry'],originalGeometry);
assert.equal(candidate.resources.damage.get(2)?.value.texture,originalDamage);
assert.equal(candidate.resources.artwork.get('art')?.value,originalArtwork);
const aborted=new AbortController();aborted.abort();await assert.rejects(prepareStickerPackRenderFrame(wire,null,aborted.signal,first.resources),{name:'AbortError'});
await assert.rejects(prepareStickerPackRenderFrame({...wire,reuse:{...reuse,damage:[999]}},null,new AbortController().signal,first.resources),/identity mismatch/);
assert.deepEqual([geometryDisposes,damageDisposes,artDisposes,closes],[0,0,0,0]);
first.dispose();first.dispose();assert.deepEqual([geometryDisposes,damageDisposes,artDisposes,closes],[0,0,0,0]);
await assert.rejects(prepareStickerPackRenderFrame(wire,null,new AbortController().signal,first.resources),/no live renderer owner/);
const next=await prepareStickerPackRenderFrame(wire,null,new AbortController().signal,candidate.resources);
candidate.dispose();assert.equal(closes,0);next.dispose();next.dispose();
assert.deepEqual([geometryDisposes,damageDisposes,artDisposes,closes],[1,1,1,1]);
geometry.port1.close();damage.port1.close();texture.dispose();
await Bun.write(new URL('./pack-reuse.json',import.meta.url),JSON.stringify({method:'Actual worker assembler and MessagePorts; controlled bitmap close boundary, no GPU rendering',exactSharedIdentity:true,failedCandidatePreservesCurrent:true,abortPreservesCurrent:true,retiredOwnerRejected:true,currentReplacementRetainsCandidate:true,finalDisposals:{geometryDisposes,damageDisposes,artDisposes,closes}},null,2)+'\n');
