import assert from 'node:assert/strict';
import {mock} from 'bun:test';
import {GlobalRegistrator} from '../../../../../../packages/device/node_modules/@happy-dom/global-registrator';
import {PerspectiveCamera} from '../../../../../../packages/device/node_modules/three/build/three.module.js';
import {prepareDeviceSteps,restorePreparedDevice,disposePreparedDevice} from '../../../../../../packages/device/src/device-preparation-data';
import {drainSteps} from '../../../../../../packages/device/src/sticker-computation-steps';
import {DEFAULT_DEVICE_FORM as form} from '../../../../../../packages/device/src/form';
import {DEFAULT_DEVICE_MATERIALS as materials} from '../../../../../../packages/device/src/materials';
import {createDeviceQueryView} from '../../../../../../packages/device/src/device-query-view';
import type {DeviceStickerScene} from '../../../../../../packages/device/src/sticker-contract';
import type {RenderPose} from '../../../../../../packages/device/src/device-render-protocol';
GlobalRegistrator.register();let preparations=0,sent=0;
mock.module('../../../../../../packages/composite/src/native-sticker-resources',()=>({prepareNativeEquippedFrame:async()=>{preparations++;return{prints:[],ports:[],artworks:[],queries:[],release(){},transferred(){}};}}));
const {createNativeStickerController}=await import('../../../../../../packages/composite/src/native-sticker-controller');
const prepared=restorePreparedDevice(drainSteps(prepareDeviceSteps(form))),query=createDeviceQueryView(prepared,form,materials),camera=new PerspectiveCamera();camera.position.z=3500;camera.updateMatrixWorld();
const layout={revision:1,cssWidth:440,cssHeight:888,backingWidth:1320,backingHeight:2664,pixelRatio:3,cameraWorld:camera.matrixWorld.toArray(),cameraProjection:camera.projectionMatrix.toArray()};
const owner=createNativeStickerController({canvas:document.createElement('canvas'),layout:()=>layout,form,query,sendEpoch(){},sendFrame(){sent++;},fail(error){throw error;}});
const scene:DeviceStickerScene={assets:[],placements:[],pack:null};
owner.update(scene);await Bun.sleep(0);assert.equal(sent,1);
owner.update({...scene});
const pose:RenderPose={sequence:1,motionEpoch:0,lastAcceptedCommand:0,layoutRevision:1,sceneRevision:1,resourceRevision:1,nodes:[],orientation:{pitchDeg:0,yawDeg:0,rollDeg:0},reveal:null};
owner.receive({type:'equipped-frame-adopted',version:1,epoch:1,sequence:1,pose});await Bun.sleep(0);
assert.equal(preparations,1,'Compatible callback/pose-only refresh while awaiting ACK must not repeat preparation');
const changed:DeviceStickerScene={...scene,assets:[{id:'one',url:'/one.png',width:10,height:10,visibleBounds:[0,0,10,10]}],placements:[{stickerId:'one',surface:'back',x:.5,y:.5,width:.2,rotationDeg:0}]};
owner.update(changed);await Bun.sleep(0);assert.equal(sent,2);owner.update(scene);owner.receive({type:'equipped-frame-rejected',version:1,epoch:1,sequence:2});await Bun.sleep(0);assert.equal(preparations,2,'A→B→A keeps admitted A when obsolete B rejects');
owner.update(changed);await Bun.sleep(0);assert.equal(sent,3);
const newer={...changed,pack:{progress:1,peel:0,landing:0,placement:null,stickerId:null,computationEpoch:9}};
owner.update(newer);owner.receive({type:'equipped-frame-rejected',version:1,epoch:1,sequence:3});await Bun.sleep(0);assert.equal(sent,4,'Epoch supersession re-prepares required candidate');
owner.receive({type:'equipped-frame-adopted',version:1,epoch:1,sequence:4,pose});owner.update({...newer});await Bun.sleep(0);assert.equal(sent,4);
const observed={preparations,sent,identicalRefreshDeduplicated:true,returnToCurrent:true,epochSupersession:true};owner.dispose();owner.rendererRetired();query.dispose();disposePreparedDevice(prepared);
await Bun.write(new URL('./reviewer-equipped-dedup.json',import.meta.url),JSON.stringify(observed,null,2)+'\n');
