import { describe, expect, test } from 'bun:test'
import { createAppleProvider, type MusicKitGlobalLike, type MusicKitInstanceLike } from './apple-provider.ts'

function fakeMusic(): MusicKitInstanceLike & { emit(name: string): void; removed: string[]; calls: string[] } {
  const listeners = new Map<string, Set<(event: unknown) => void>>(); const calls: string[] = []; const removed: string[] = []
  return {
    api: { async music(path) { if (path.includes('/library/playlists')) return { data: { data: [{ id: 'p.1', type: 'library-playlists', attributes: { name: 'Focus', canEdit: true, playParams: { globalId: 'pl.1' } } }], next: '/v1/me/library/playlists?offset=1', meta: { total: 2 } } }; return { data: { data: [] } } } },
    isAuthorized: true, storefrontId: 'se', volume: 0.5, shuffleMode: 0, repeatMode: 0, playbackState: 3, currentPlaybackTime: 12, currentPlaybackDuration: 240,
    async authorize() { calls.push('authorize'); return 'opaque-user' }, async unauthorize() { calls.push('unauthorize') }, async setQueue() { calls.push('setQueue') }, async play() { calls.push('play') }, async pause() { calls.push('pause') }, async skipToNextItem() { calls.push('next') }, async skipToPreviousItem() { calls.push('previous') }, async seekToTime(value) { calls.push(`seek:${String(value)}`) }, async playLater() { calls.push('later') }, async playNext() { calls.push('nextQueue') },
    addEventListener(name, callback) { const set = listeners.get(name) ?? new Set(); set.add(callback); listeners.set(name, set) }, removeEventListener(name, callback) { listeners.get(name)?.delete(callback); removed.push(name) }, emit(name) { for (const callback of listeners.get(name) ?? []) callback({}) }, removed, calls,
  }
}
function setup() { const music = fakeMusic(); const kit: MusicKitGlobalLike = { async configure() { return music }, getInstance() { return music }, PlaybackStates: { playing: 3 }, PlayerShuffleMode: { off: 0, songs: 1, albums: 2 }, PlayerRepeatMode: { off: 0, one: 1, all: 2 } }; return { music, provider: createAppleProvider({ async loadMusicKit() { return kit }, async fetchDeveloperToken() { return { token: 'test-token-never-logged', expiresAt: 2_000 } } }) } }

describe('Apple provider', () => {
  test('configures, authorizes, signs out, and reports storefront', async () => { const { provider, music } = setup(); const sessions: unknown[] = []; const off = provider.onSessionChange((value) => sessions.push(value)); await provider.configure(); const session = await provider.authorize(); expect(session.storefront).toBe('se'); expect(session.userIdentifier).toBe('opaque-user'); await provider.unauthorize(); off(); expect(sessions.at(-1)).toBeNull(); expect(music.calls).toContain('unauthorize') })
  test('maps library pages, preserves stable local identity, and rejects invented cursors', async () => { const { provider } = setup(); await provider.configure(); const first = await provider.libraryList('playlists'); expect(first.total).toBe(2); expect(first.items[0]?.kind).toBe('playlist'); const firstKey = first.items[0]?.key; const again = await provider.libraryList('playlists'); expect(again.items[0]?.key).toBe(firstKey); await expect(provider.libraryList('playlists', '/invented')).rejects.toHaveProperty('_tag', 'InvalidCursor') })
  test('subscribes to playback and removes consumer callbacks cleanly', async () => { const { provider, music } = setup(); await provider.configure(); let changes = 0; let ticks = 0; const offState = provider.onPlaybackChange(() => { changes += 1 }); const offTick = provider.onProgress(() => { ticks += 1 }); music.emit('playbackStateDidChange'); music.emit('playbackTimeDidChange'); expect(changes).toBe(1); expect(ticks).toBe(1); offState(); offTick(); music.emit('playbackStateDidChange'); music.emit('playbackTimeDidChange'); expect(changes).toBe(1); expect(ticks).toBe(1) })
  test('drives documented transport primitives', async () => { const { provider, music } = setup(); await provider.configure(); await provider.play(); await provider.pause(); await provider.seek(500_000); await provider.skip('next'); expect(music.calls).toEqual(expect.arrayContaining(['play', 'pause', 'seek:240', 'next'])) })
})
