import { chromium } from '../../../../../packages/panel/node_modules/@playwright/test/index.mjs'
import { installDeterministicAppleMusic } from '../../../../../apps/web/tests/deterministic-apple-music'
import {writeFile,readFile}from'node:fs/promises'
import {createHash}from'node:crypto'
import{resolve}from'node:path'
const files=['packages/device/src/Device.tsx','packages/device/src/layout.ts','packages/device/src/surface-layout.ts','packages/device/src/screen-geometry.ts','packages/device/src/screen-aperture.ts'];async function hashes(){return Object.fromEntries(await Promise.all(files.map(async p=>[p,createHash('sha256').update(await readFile(p)).digest('hex')])))}
const before=await hashes();const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--enable-blink-features=CanvasDrawElement']});const page=await browser.newPage({viewport:{width:1200,height:900},deviceScaleFactor:3});await installDeterministicAppleMusic(page);await page.goto('http://localhost:3000/_spike/device?capture=');await page.waitForSelector('.wp-panel');await page.waitForTimeout(500);const results=[]
for(const colourway of ['black','white'] as const)for(const pose of ['front','quarter']){
 await page.evaluate(({colourway,pose})=>{window.__webpodDevicePreview!.setColourway(colourway);window.__webpodDevicePreview!.setOrientation(pose==='front'?{pitchDeg:0,yawDeg:0,rollDeg:0}:{pitchDeg:10,yawDeg:-48,rollDeg:-2})},{colourway,pose});await page.waitForTimeout(200)
 results.push(await page.evaluate(async({colourway,pose})=>{
 const urls=performance.getEntriesByType('resource').map(e=>e.name);const fiber=await import(urls.find(n=>n.includes('/@react-three_fiber.js'))!);const{Vector3,Raycaster}=await import(urls.find(n=>n.includes('/three.js?'))!);const state=[...fiber._roots.values()][0].store.getState();let lcd:any;state.scene.traverse((o:any)=>{if(o.material?.name?.startsWith('webpod-lcd-'))lcd=o});lcd.geometry.computeBoundingBox();const bounds=lcd.geometry.boundingBox;const origin=state.camera.getWorldPosition(new Vector3());const rayAt=(x:number,y:number)=>{const target=new Vector3(x,y,bounds.max.z).applyMatrix4(lcd.matrixWorld);const ray=new Raycaster(origin,target.clone().sub(origin).normalize());const hits=ray.intersectObjects(state.scene.children,true).filter((h:any)=>{let p=h.object;while(p){if(!p.visible)return false;p=p.parent}return h.object.material&&!h.object.material.transparent});return{targetDistance:target.distanceTo(origin),hit:hits[0]}}
 const active=[];for(const sx of [-1,1])for(const sy of [-1,1]){const x=sx*(136-.425),y=sy*(102-.425),r=rayAt(x,y);active.push({x,y,firstOpaqueIsLcd:r.hit?.object===lcd,firstOpaque:r.hit?.object.name??null,nearerBy:r.hit?r.targetDistance-r.hit.distance:null})}
 const annulus=[];const check=(x:number,y:number,kind:string)=>{const r=rayAt(x,y);const name=r.hit?.object.name??null;annulus.push({x,y,kind,firstOpaque:name,covered:['device-display-mask','device-display-well','device-body'].includes(name)})}
 for(const offset of [.25,1,3,5.5,6,6.6,6.75,7,8,10])for(const sign of [-1,1])for(const f of [-.95,-.5,0,.5,.95]){check(sign*(136+offset),102*f,'vertical');check(136*f,sign*(102+offset),'horizontal')}
 for(const radius of [.25,1,3,5.5,6,6.6,7,8,10])for(const sx of [-1,1])for(const sy of [-1,1])for(const angle of [15,30,45,60,75])check(sx*(136+radius*Math.cos(angle*Math.PI/180)),sy*(102+radius*Math.sin(angle*Math.PI/180)),'corner')
 return{colourway,pose,active,annulusCount:annulus.length,annulusFailures:annulus.filter((s:any)=>!s.covered),activeFailures:active.filter(s=>!s.firstOpaqueIsLcd),annulus}
 },{colourway,pose}))
}
await browser.close();const after=await hashes();await writeFile(resolve(import.meta.dirname,'results.json'),JSON.stringify({before,after,sourcesStable:JSON.stringify(before)===JSON.stringify(after),results},null,2));console.log(JSON.stringify(results.map(r=>({colourway:r.colourway,pose:r.pose,annulusCount:r.annulusCount,annulusFailures:r.annulusFailures,activeFailures:r.activeFailures}))))
