import { computeStickerTransaction } from '../../../../../../packages/device/src/sticker-transaction-computation';
import { drainSteps } from '../../../../../../packages/device/src/sticker-computation-steps';
import assert from 'node:assert/strict';
import { acquireStickerTransaction, requestStickerTransaction, acquirePrivateStickerTransaction, releaseUnusedStickerTransactions, inspectStickerTransactions } from '../../../../../../packages/device/src/sticker-transaction-broker';
import { DEFAULT_DEVICE_FORM } from '../../../../../../packages/device/src/form';
import { stickerTransactionBuffers, type StickerSurfaceRequest, type StickerTransactionResponse } from '../../../../../../packages/device/src/sticker-transaction-data';
const input: StickerSurfaceRequest = { kind: 'surface', art: { id: 'lease-proof', url: 'proof', width: 96, height: 128, visibleBounds: [0, 0, 96, 128] }, placement: { stickerId: 'lease-proof', surface: 'back', x: .5, y: .5, width: .2, rotationDeg: 15 }, form: DEFAULT_DEVICE_FORM };
const key = 'surface:lease-proof';
const main = acquireStickerTransaction(key,input), shared = acquireStickerTransaction(key,input);
assert.equal(main.result, shared.result);
const result = await main.result;
assert.equal(result.kind,'surface');
if(result.kind!=='surface')throw Error('surface result');
const positions=result.geometry.attributes['position']?.array,uv=result.geometry.attributes['uv']?.array,normals=result.geometry.attributes['normal']?.array;
assert(positions instanceof Float32Array && uv instanceof Float32Array && normals instanceof Float32Array);
const damage=acquireStickerTransaction('damage:lease-proof',{kind:'damage',artworkKey:'proof',stickerId:'lease-proof',mask:{width:32,height:32,pixels:new Uint8Array(1024).fill(255)},surface:{normals,uv}});
const damageResult=await damage.result;if(damageResult.kind!=='damage')throw Error('damage result');
const contourInput={kind:'contour' as const,damageKey:'damage:lease-proof',geometryKey:key,field:damageResult.field,positions,uv,wear:.4};
const contour=acquireStickerTransaction('contour:lease-proof',contourInput);assert.deepEqual(await contour.result,drainSteps(computeStickerTransaction(contourInput)));
contour.release();damage.release();releaseUnusedStickerTransactions();
const originalBytes = stickerTransactionBuffers(result).map(buffer=>buffer.byteLength);
const abandoned = new AbortController();
const abandonedWork = requestStickerTransaction('surface:abandoned', { ...input, placement: { ...input.placement, x: .7 } }, abandoned.signal);
abandoned.abort(); await assert.rejects(abandonedWork); assert.equal(inspectStickerTransactions().worker, true);
// The following private copy succeeds through that same canonical producer after
// the abandoned single active job finishes; ordinary gesture cancellation cannot
// destroy all resident resources or queue uncharged native work.
const channel = new MessageChannel();
const delivered = new Promise<StickerTransactionResponse>(resolve=>{channel.port2.onmessage=(event: MessageEvent<StickerTransactionResponse>)=>resolve(event.data);});
const renderer = await acquirePrivateStickerTransaction(key,input,channel.port1,new AbortController().signal);
const response = await delivered; assert('result' in response); assert.equal(response.id,renderer.resourceId);
assert.deepEqual(response.result,result);
structuredClone(response.result,{transfer:stickerTransactionBuffers(response.result)});
assert.deepEqual(stickerTransactionBuffers(result).map(buffer=>buffer.byteLength),originalBytes);
const admitted=inspectStickerTransactions();assert.equal(admitted.privateOwners,1);assert.equal(admitted.pendingCopies,0);
assert.equal(admitted.privateBytes,originalBytes.reduce((a,b)=>a+b,0));
renderer.release();renderer.release();channel.port2.close();assert.equal(inspectStickerTransactions().privateOwners,0);
main.release();assert.equal(inspectStickerTransactions().worker,true);
const pendingChannel=new MessageChannel(),cancel=new AbortController();
const pending=acquirePrivateStickerTransaction(key,input,pendingChannel.port1,cancel.signal);
for(let i=0;i<10&&inspectStickerTransactions().pendingCopies===0;i++)await Promise.resolve();
assert.equal(inspectStickerTransactions().pendingCopies,1);cancel.abort();await assert.rejects(pending);pendingChannel.port2.close();
assert.equal(inspectStickerTransactions().privateOwners,0);assert.equal(inspectStickerTransactions().privateBytes,0);
assert.equal(inspectStickerTransactions().worker,false);
const missing=new MessageChannel();await assert.rejects(acquirePrivateStickerTransaction(key,input,missing.port1,new AbortController().signal),/Canonical/);missing.port2.close();
assert.deepEqual(stickerTransactionBuffers(result).map(buffer=>buffer.byteLength),originalBytes);
shared.release();releaseUnusedStickerTransactions();assert.equal(inspectStickerTransactions().entries,0);
const fallbackDescriptor=Object.getOwnPropertyDescriptor(globalThis,'Worker');
Object.defineProperty(globalThis,'Worker',{configurable:true,value:undefined});
const fallback=acquireStickerTransaction('fallback',input);
assert.equal(inspectStickerTransactions().active!==null,true);
assert.deepEqual(await fallback.result,result);fallback.release();releaseUnusedStickerTransactions();
if(fallbackDescriptor)Object.defineProperty(globalThis,'Worker',fallbackDescriptor);
const evidence={method:'Actual Bun module worker/MessagePorts; worker-unavailable exact cooperative recovery. Not browser or mobile timing.',checks:{sharedPromise:true,canonicalContourReferencesExact:true,ordinaryCancellationPreservesCanonicalProducer:true,privateExactCopy:true,mountedBuffersNotDetached:true,privateBytesAndOwnerCount:true,idempotentRelease:true,pendingAbortRetiresProducer:true,canonicalLossRejectsWithoutRecompute:true,finalCleanup:true,exactCooperativeFallback:true},admitted};
await Bun.write(new URL('./lifecycle.json',import.meta.url),JSON.stringify(evidence,null,2)+'\n');console.log(evidence);
