import assert from 'node:assert/strict';
import { BufferGeometry, Mesh, PerspectiveCamera } from '../../../../../../packages/device/node_modules/three/build/three.module.js';
import { createStickerSurfaceGeometry } from '../../../../../../packages/device/src/sticker-surface';
import { createStickerWrapSurface } from '../../../../../../packages/device/src/sticker-wrap';
import { DEFAULT_DEVICE_FORM } from '../../../../../../packages/device/src/form';
import { createStickerDamageField } from '../../../../../../packages/device/src/sticker-alpha';
import { drainSteps } from '../../../../../../packages/device/src/sticker-computation-steps';
import { prepareStickerContourSteps } from '../../../../../../packages/device/src/sticker-contour-computation';
import { setPreparedStickerContour, preparedStickerContourWear } from '../../../../../../packages/device/src/sticker-contour-preparation-data';
import { projectStickerContourField } from '../../../../../../packages/device/src/sticker-contour';
const rear=new BufferGeometry(), art={id:'review',url:'review',width:96,height:128,visibleBounds:[0,0,96,128] as const};
const geometry=createStickerSurfaceGeometry(art,{stickerId:art.id,surface:'back',x:.5,y:.5,width:.3,rotationDeg:0},rear,createStickerWrapSurface(DEFAULT_DEVICE_FORM,[]));
const field=createStickerDamageField({width:96,height:128,pixels:new Uint8Array(96*128).fill(255)},art.id);
const positions=geometry.getAttribute('position'),uv=geometry.getAttribute('uv');
if(!(positions.array instanceof Float32Array)||!(uv.array instanceof Float32Array))throw Error('float fixture');
setPreparedStickerContour(geometry,field,0,drainSteps(prepareStickerContourSteps(field,0,positions.array,uv.array)));
const mesh=new Mesh(geometry),camera=new PerspectiveCamera(30,1,1,4000);camera.position.z=1200;camera.updateMatrixWorld();
const canvas={left:0,top:0,width:440,height:956};
const query=(wear:number)=>projectStickerContourField(mesh,camera,canvas,field,wear);
const before=query(0); assert(before); assert.equal(preparedStickerContourWear(geometry), 0);
const wearPrepared=query(1);mesh.geometry=geometry.clone();const wearExact=query(1);mesh.geometry.dispose();mesh.geometry=geometry;
for(let i=0;i<positions.count;i++)positions.setX(i,positions.getX(i)+15);positions.needsUpdate=true;
assert.equal(preparedStickerContourWear(geometry), undefined);
const mutationPrepared=query(0);mesh.geometry=geometry.clone();const mutationExact=query(0);
assert.deepEqual(wearPrepared, wearExact);
assert.deepEqual(mutationPrepared, mutationExact);
console.log(JSON.stringify({wearMismatch:false,positionMutationMismatch:false,exactDefensiveFallback:true}));
mesh.geometry.dispose();geometry.dispose();rear.dispose();mesh.material.dispose();
